#!/usr/bin/env python3
"""Writes the content_files rows (which file belongs to which item, and whether it is free)
from the app catalog, for the download-url function. Run after changing the catalog:
    python3 tool/content_files_sql.py > supabase/migrations/<timestamp>_content_files_rows.sql
Studio publishing will keep this table up to date later (ARCHITECTURE §6)."""
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
catalog = json.loads((ROOT / "app/assets/mock/catalog.json").read_text())
rows = []
for item in catalog["items"]:
    free = "true" if item.get("access") == "free" else "false"
    pack = f"'{item['pack_id']}'" if item.get("pack_id") else "null"
    assets = list(item.get("audio", [])) + list(item.get("pdf", []))
    for asset in (item.get("script") or {}).get("assets", {}).values() if isinstance((item.get("script") or {}).get("assets"), dict) else []:
        if isinstance(asset, dict) and "path" in asset:
            assets.append(asset)
    for asset in assets:
        rows.append(f"  ('{asset['path']}', '{item['id']}', {pack}, {free})")
print("-- Generated by tool/content_files_sql.py from app/assets/mock/catalog.json.")
print("insert into public.content_files (path, item_id, pack_id, free) values")
print(",\n".join(sorted(set(rows))))
print("on conflict (path) do update set item_id = excluded.item_id, pack_id = excluded.pack_id, free = excluded.free;")
