#!/usr/bin/env bash
# Sets up signed download links for recordings on the LH.pl hosting. Run it yourself:
#   tool/set_files_secrets.sh https://pliki.audiokiddo.pl
# A new signing key is generated here, stored in Supabase and written straight into
# config.php of a ready-to-upload folder (never printed); a copy goes to the clipboard for
# the password manager. Running it again creates a NEW key: upload config.php again.
set -euo pipefail
cd "$(dirname "$0")/.."

base=${1:-}
[[ $base == https://* ]] || { echo "Podaj adres folderu z get.php, np. tool/set_files_secrets.sh https://pliki.audiokiddo.pl"; exit 1; }
[[ -d dev_content/audio ]] || { echo "Brak folderu dev_content z nagraniami. Nic nie zapisano."; exit 1; }
key=$(openssl rand -hex 32)

env_file=$(mktemp)
chmod 600 "$env_file"
trap 'rm -f "$env_file"' EXIT
printf 'FILES_BASE_URL=%s\nDOWNLOAD_SIGNING_KEY=%s\n' "${base%/}" "$key" > "$env_file"
supabase secrets set --env-file "$env_file"

# Folder to upload over FTP / the LH.pl file manager, laid out like the hosting account:
#   public_html/<subdomain>/get.php + config.php   and   audiokiddo-pliki/ next to public_html.
host=${base#https://}; host=${host%%/*}
out="../AudioKiddo-na-serwer"
rm -rf "$out"
mkdir -p "$out/public_html/$host" "$out/audiokiddo-pliki"
cp tool/lhpl/get.php "$out/public_html/$host/"
cp -R dev_content/audio dev_content/games dev_content/pdf "$out/audiokiddo-pliki/"
umask 077
cat > "$out/public_html/$host/config.php" <<PHP
<?php
// Generated by tool/set_files_secrets.sh. Keep it private; never commit it.
return [
    'DOWNLOAD_SIGNING_KEY' => '$key',
    // audiokiddo-pliki sits next to public_html, outside the public folders.
    'FILES_ROOT' => dirname(__DIR__, 2) . '/audiokiddo-pliki',
];
PHP

printf '%s' "$key" | pbcopy
echo
echo "Gotowe. Klucz jest w Supabase, w config.php i w schowku (nigdzie nie wyświetlony)."
echo "1. Zapisz klucz ze schowka w aplikacji Hasła jako „AudioKiddo – klucz linków do plików”."
echo "2. Wgraj na serwer zawartość folderu: $(cd "$out" && pwd)"
echo "   public_html/$host/ → do katalogu subdomeny, audiokiddo-pliki/ → obok public_html."
