#!/usr/bin/env bash
# Sets up signed download links for recordings on the LH.pl hosting. Run it yourself:
#   tool/set_files_secrets.sh https://pliki.audiokiddo.pl
# A new signing key is generated here, stored in Supabase and written straight into
# config.php of a ready-to-upload folder (never printed); a copy goes to the clipboard for
# the password manager. Running it again creates a NEW key: upload config.php again.
set -euo pipefail
cd "$(dirname "$0")/.."

base=${1:-}
[[ $base == https://* ]] || { echo "Podaj adres folderu z get.php, np. tool/set_files_secrets.sh https://pliki.audiokiddo.pl"; exit 1; }
[[ -d dev_content/audio ]] || { echo "Brak folderu dev_content z nagraniami. Nic nie zapisano."; exit 1; }
key=$(openssl rand -hex 32)

env_file=$(mktemp)
chmod 600 "$env_file"
trap 'rm -f "$env_file"' EXIT
printf 'FILES_BASE_URL=%s\nDOWNLOAD_SIGNING_KEY=%s\n' "${base%/}" "$key" > "$env_file"
supabase secrets set --env-file "$env_file"

# One folder for the subdomain's directory (public_html/<subdomain>) and the same as a ZIP for
# the LH.pl file manager: get.php, config.php and nagrania/ with the recordings, which its
# .htaccess closes to the web (only get.php reads them, after checking the signed link).
host=${base#https://}; host=${host%%/*}
out="../AudioKiddo-na-serwer"
site="$out/$host"
rm -rf "$out"
mkdir -p "$site/nagrania"
cp tool/lhpl/get.php "$site/"
cp -R dev_content/audio dev_content/games dev_content/pdf "$site/nagrania/"
printf 'Require all denied\n' > "$site/nagrania/.htaccess"
printf '<Files "config.php">\n  Require all denied\n</Files>\nOptions -Indexes\n' > "$site/.htaccess"
umask 077
cat > "$site/config.php" <<PHP
<?php
// Generated by tool/set_files_secrets.sh. Keep it private; never commit it.
return [
    'DOWNLOAD_SIGNING_KEY' => '$key',
    // Recordings next to get.php, closed to the web by nagrania/.htaccess.
    'FILES_ROOT' => __DIR__ . '/nagrania',
];
PHP
(cd "$site" && zip -qr -X "../paczka-na-serwer.zip" . -x '.DS_Store' '*/.DS_Store')

printf '%s' "$key" | pbcopy
echo
echo "Gotowe. Klucz jest w Supabase, w config.php i w schowku (nigdzie nie wyświetlony)."
echo "1. Zapisz klucz ze schowka w aplikacji Hasła jako „AudioKiddo – klucz linków do plików”."
echo "2. Wgraj $(cd "$out" && pwd)/paczka-na-serwer.zip do katalogu public_html/$host"
echo "   (Menedżer plików LH.pl) i rozpakuj go tam. Potem usuń ZIP z serwera i folder AudioKiddo-na-serwer z komputera."
