-- Time estimates for the launch plan tasks (Dawid has about 6 hours a day) and what Claude
-- already prepared for them, added to each task's note once.

update public.crm_items c
set data = c.data || jsonb_build_object('hours', v.hours),
    body = case when c.body = '' then v.note else c.body || ' ' || v.note end
from (values
  ('f1-apple', 1, 'Czas: ok. 1 h.'),
  ('f1-google', 1.5, 'Czas: ok. 1,5 h.'),
  ('f1-legal', 0.5, 'Czas: ok. 30 min.'),
  ('f1-deploy', 0.5, 'Czas: ok. 30 min.'),
  ('f1-decisions', 1, 'Czas: ok. 1 h.'),
  ('f1-invite', 0.25, 'Czas: ok. 15 min.'),
  ('f1-pages', 1.5, 'Czas: ok. 1,5 h. Claude przygotował: kod stron: docs/strona/sklepy/.'),
  ('f1-testers', 2, 'Czas: ok. 2 h. Claude przygotował: wiadomość do testerów: docs/marketing/PREMIERA-TEKSTY.md.'),
  ('f1-business', 1.5, 'Czas: ok. 1,5 h.'),
  ('f1-apple-setup', 2, 'Czas: ok. 2 h.'),
  ('f1-android-key', 0.5, 'Czas: ok. 30 min.'),
  ('f1-testflight', 2, 'Czas: ok. 2 h.'),
  ('f1-closed', 1, 'Czas: ok. 1 h.'),
  ('f1-products', 3, 'Czas: ok. 3 h.'),
  ('f1-preorder', 0.5, 'Czas: ok. 30 min.'),
  ('f1-social', 1, 'Czas: ok. 1 h. Claude przygotował: teksty postu, relacji i newslettera: docs/marketing/PREMIERA-TEKSTY.md.'),
  ('f1-diag', 2, 'Czas: ok. 2 h.'),
  ('f1-qa', 3, 'Czas: ok. 3 h.'),
  ('f1-video', 3, 'Czas: ok. 3 h. Claude przygotował: scenariusz 30 s: docs/sklepy/WYROZNIENIE.md, sekcja 7.'),
  ('f1-listing', 2, 'Czas: ok. 2 h. Claude przygotował: karta do wklejenia, zrzuty i grafiki: docs/sklepy/KARTA-DO-WKLEJENIA.md.'),
  ('f1-measure', 3, 'Czas: ok. 3 h.'),
  ('f1-submit', 0.5, 'Czas: ok. 30 min.'),
  ('f1-nominate', 0.5, 'Czas: ok. 30 min. Claude przygotował: tekst zgłoszenia: dokument „AudioKiddo w sklepach”.'),
  ('f2-android-prod', 0.5, 'Czas: ok. 30 min.'),
  ('f2-soft', 0.5, 'Czas: ok. 30 min.'),
  ('f2-b2b', 4, 'Czas: ok. 4 h. Claude przygotował: oferta i mail: docs/marketing/przedszkola/.'),
  ('f2-ratings', 0.5, 'Czas: ok. 30 min. Claude przygotował: wiadomość z prośbą o ocenę: docs/marketing/PREMIERA-TEKSTY.md.'),
  ('f2-reels', 8, 'Czas: ok. 8 h. Claude przygotował: scenariusze rolek: docs/marketing/ROLKI-I-REKLAMY.md.'),
  ('f2-event-art', 0.25, 'Czas: ok. 15 min. Claude przygotował: gotowe: docs/sklepy/grafiki/ (wystarczy sprawdzić).'),
  ('f2-premiere-event', 1, 'Czas: ok. 1 h. Claude przygotował: teksty i obrazki wydarzenia: KARTA-DO-WKLEJENIA.md.'),
  ('f2-influ', 3, 'Czas: ok. 3 h. Claude przygotował: wiadomość do influencerek: docs/marketing/PREMIERA-TEKSTY.md.'),
  ('f2-gift', 3, 'Czas: ok. 3 h. Claude przygotował: strona, kartka i instrukcja: docs/marketing/PREZENT.md.'),
  ('f2-ads-setup', 3, 'Czas: ok. 3 h.'),
  ('f2-kpi', 1, 'Czas: ok. 1 h.'),
  ('f2-mail-premiere', 0.5, 'Czas: ok. 30 min. Claude przygotował: newsletter premierowy: docs/marketing/PREMIERA-TEKSTY.md.'),
  ('f3-launch', 2, 'Czas: ok. 2 h.'),
  ('f3-launch-social', 1.5, 'Czas: ok. 1,5 h. Claude przygotował: post i relacje premierowe: docs/marketing/PREMIERA-TEKSTY.md.'),
  ('f3-reviews', 0.25, 'Czas: ok. 15 min.'),
  ('f3-stability', 2, 'Czas: ok. 2 h.'),
  ('f3-ads-check', 1.5, 'Czas: ok. 1,5 h.'),
  ('f3-bf', 2, 'Czas: ok. 2 h.'),
  ('f3-gift-campaign', 4, 'Czas: ok. 4 h.'),
  ('f3-ab', 1, 'Czas: ok. 1 h.'),
  ('f3-year', 2, 'Czas: ok. 2 h.'),
  ('f4-ads-scale', 1.5, 'Czas: ok. 1,5 h.'),
  ('f4-teacher', 1, 'Czas: ok. 1 h.'),
  ('f4-b2b2', 3, 'Czas: ok. 3 h.'),
  ('f4-dd-week', 3, 'Czas: ok. 3 h.'),
  ('f4-half', 2, 'Czas: ok. 2 h.'),
  ('p-grudzien-0', 2, 'Czas: ok. 2 h.'),
  ('p-grudzien-1', 0.5, 'Czas: ok. 30 min.'),
  ('p-grudzien-2', 8, 'Czas: ok. 8 h.'),
  ('p-grudzien-3', 8, 'Czas: ok. 8 h.'),
  ('p-grudzien-4', 8, 'Czas: ok. 8 h.'),
  ('p-grudzien-5', 3, 'Czas: ok. 3 h.'),
  ('p-grudzien-6', 1, 'Czas: ok. 1 h.'),
  ('p-grudzien-7', 3, 'Czas: ok. 3 h.'),
  ('p-grudzien-8', 0.5, 'Czas: ok. 30 min.'),
  ('p-grudzien-9', 1.5, 'Czas: ok. 1,5 h.'),
  ('p-grudzien-10', 1, 'Czas: ok. 1 h.'),
  ('p-styczen-0', 2, 'Czas: ok. 2 h.'),
  ('p-styczen-1', 0.5, 'Czas: ok. 30 min.'),
  ('p-styczen-2', 8, 'Czas: ok. 8 h.'),
  ('p-styczen-3', 8, 'Czas: ok. 8 h.'),
  ('p-styczen-4', 8, 'Czas: ok. 8 h.'),
  ('p-styczen-5', 3, 'Czas: ok. 3 h.'),
  ('p-styczen-6', 1, 'Czas: ok. 1 h.'),
  ('p-styczen-7', 3, 'Czas: ok. 3 h.'),
  ('p-styczen-8', 0.5, 'Czas: ok. 30 min.'),
  ('p-styczen-9', 1.5, 'Czas: ok. 1,5 h.'),
  ('p-styczen-10', 1, 'Czas: ok. 1 h.'),
  ('p-luty-0', 2, 'Czas: ok. 2 h.'),
  ('p-luty-1', 0.5, 'Czas: ok. 30 min.'),
  ('p-luty-2', 8, 'Czas: ok. 8 h.'),
  ('p-luty-3', 8, 'Czas: ok. 8 h.'),
  ('p-luty-4', 8, 'Czas: ok. 8 h.'),
  ('p-luty-5', 3, 'Czas: ok. 3 h.'),
  ('p-luty-6', 1, 'Czas: ok. 1 h.'),
  ('p-luty-7', 3, 'Czas: ok. 3 h.'),
  ('p-luty-8', 0.5, 'Czas: ok. 30 min.'),
  ('p-luty-9', 1.5, 'Czas: ok. 1,5 h.'),
  ('p-luty-10', 1, 'Czas: ok. 1 h.'),
  ('p-marzec-0', 2, 'Czas: ok. 2 h.'),
  ('p-marzec-1', 0.5, 'Czas: ok. 30 min.'),
  ('p-marzec-2', 8, 'Czas: ok. 8 h.'),
  ('p-marzec-3', 8, 'Czas: ok. 8 h.'),
  ('p-marzec-4', 8, 'Czas: ok. 8 h.'),
  ('p-marzec-5', 3, 'Czas: ok. 3 h.'),
  ('p-marzec-6', 1, 'Czas: ok. 1 h.'),
  ('p-marzec-7', 3, 'Czas: ok. 3 h.'),
  ('p-marzec-8', 0.5, 'Czas: ok. 30 min.'),
  ('p-marzec-9', 1.5, 'Czas: ok. 1,5 h.'),
  ('p-marzec-10', 1, 'Czas: ok. 1 h.'),
  ('p-kwiecien-0', 2, 'Czas: ok. 2 h.'),
  ('p-kwiecien-1', 0.5, 'Czas: ok. 30 min.'),
  ('p-kwiecien-2', 8, 'Czas: ok. 8 h.'),
  ('p-kwiecien-3', 8, 'Czas: ok. 8 h.'),
  ('p-kwiecien-4', 8, 'Czas: ok. 8 h.'),
  ('p-kwiecien-5', 3, 'Czas: ok. 3 h.'),
  ('p-kwiecien-6', 1, 'Czas: ok. 1 h.'),
  ('p-kwiecien-7', 3, 'Czas: ok. 3 h.'),
  ('p-kwiecien-8', 0.5, 'Czas: ok. 30 min.'),
  ('p-kwiecien-9', 1.5, 'Czas: ok. 1,5 h.'),
  ('p-kwiecien-10', 1, 'Czas: ok. 1 h.'),
  ('p-maj-0', 2, 'Czas: ok. 2 h.'),
  ('p-maj-1', 0.5, 'Czas: ok. 30 min.'),
  ('p-maj-2', 8, 'Czas: ok. 8 h.'),
  ('p-maj-3', 8, 'Czas: ok. 8 h.'),
  ('p-maj-4', 8, 'Czas: ok. 8 h.'),
  ('p-maj-5', 3, 'Czas: ok. 3 h.'),
  ('p-maj-6', 1, 'Czas: ok. 1 h.'),
  ('p-maj-7', 3, 'Czas: ok. 3 h.'),
  ('p-maj-8', 0.5, 'Czas: ok. 30 min.'),
  ('p-maj-9', 1.5, 'Czas: ok. 1,5 h.'),
  ('p-maj-10', 1, 'Czas: ok. 1 h.')
) as v(key, hours, note)
where c.data->>'plan' = 'premiera-2026' and c.data->>'key' = v.key and not (c.data ? 'hours');
