-- The launch plan (docs: „Harmonogram premiery AudioKiddo”): tasks for Dawid, Nela or both on
-- the CRM board and dated entries in the calendar, from the store accounts on 8 October 2026 to
-- Children's Day 2027, with a new pack every month. Each row carries its plan key, so running
-- this again adds nothing twice and keeps what was moved, done or deleted on the board.

-- The two account tasks from the CRM start now come from the plan (owned by Nela).
update public.crm_items set status = 'archived'
where source = 'system' and kind = 'task' and status = 'todo'
  and title in ('Założyć konto Apple Developer', 'Założyć konto Google Play Console');

insert into public.crm_items (kind, area, title, body, status, priority, owner, due, source, data)
select v.kind, v.area, v.title, v.body, 'todo', v.priority, v.owner, v.due, 'system',
       jsonb_build_object('plan', 'premiera-2026', 'key', v.key)
from (values
  ('f1-apple', 'task', 'launch', 'Konto Apple Developer na Apple ID Neli', 'Aplikacja Apple Developer → Account → Enroll Now → Individual / Sole Proprietor, 99 USD. Kroki: dokument „AudioKiddo w sklepach”.', 1, 'Nela', date '2026-10-08'),
  ('f1-google', 'task', 'launch', 'Konto Google Play Console (osobiste, na Nelę)', 'play.google.com/console/signup, 25 USD, weryfikacja dowodu i telefonu z Androidem. Bez D-U-N-S.', 1, 'Razem', date '2026-10-09'),
  ('f1-legal', 'task', 'launch', 'Polityka prywatności i regulamin aplikacji do prawnika', 'docs/prawne/polityka-prywatnosci-aplikacji.md i regulamin-aplikacji.md. Dopisać plany dla 2 i 3–5 dzieci.', 2, 'Nela', date '2026-10-10'),
  ('f1-decisions', 'task', 'launch', 'Decyzje: Kids 6–8 lat, ceny planów rodzinnych, premiera 16.11', 'Szczegóły: dokument „AudioKiddo w sklepach”, sekcja Decyzje.', 1, 'Razem', date '2026-10-12'),
  ('f1-deploy', 'task', 'server', 'Wgrać zaległe zmiany na serwer', 'supabase db push, supabase functions deploy (admin, woo-webhook), sekrety prezentów. docs/PUBLIKACJA.md, etap 1.', 1, 'Dawid', date '2026-10-12'),
  ('f1-invite', 'task', 'launch', 'Dodać Dawida jako administratora w App Store Connect i Play Console', '', 2, 'Nela', date '2026-10-12'),
  ('f1-pages', 'task', 'launch', 'Strony na audiokiddo.pl: polityka, kontakt, usuwanie konta, regulamin', 'Kod w docs/strona/sklepy/. Sklepy nie przyjmą aplikacji bez tych adresów. docs/PUBLIKACJA.md, etap 3.', 1, 'Dawid', date '2026-10-13'),
  ('f1-business', 'task', 'launch', 'Umowy i wypłaty: Paid Apps, konto bankowe, W-8BEN, profil płatności Google', 'Bez tego zakupy nie działają nawet w testach. Robi właścicielka konta.', 1, 'Nela', date '2026-10-14'),
  ('f1-testers', 'task', 'launch', 'Zebrać 16–18 testerów Androida (adresy Gmail)', 'Znajomi rodzice, rodzina, klienci z Empiku i sklepu. Wiadomość: docs/marketing/SKLEPY-SZYBKA-SCIEZKA.md. Każdy dostaje kod na 90 dni.', 1, 'Nela', date '2026-10-14'),
  ('f1-android-key', 'task', 'launch', 'Android: klucz przesyłania, key.properties i kopia zapasowa', 'docs/PUBLIKACJA.md, etap 5.', 1, 'Dawid', date '2026-10-15'),
  ('f1-apple-setup', 'task', 'launch', 'Apple: identyfikatory, App Group, aplikacja w App Store Connect, podpisywanie', 'docs/PUBLIKACJA.md, etap 4.', 1, 'Dawid', date '2026-10-15'),
  ('f1-closed', 'task', 'launch', 'Google: test zamknięty z 12+ testerami', 'Testowanie → Testy zamknięte. 14 dni bez przerwy liczy się od dnia, w którym 12 osób ma aplikację. Koniec ok. 30.10.', 1, 'Dawid', date '2026-10-16'),
  ('f1-testflight', 'task', 'launch', 'Pierwsza wersja w TestFlight i w teście wewnętrznym Google', 'tool/release_build.sh ios / android. docs/PUBLIKACJA.md, etap 7.', 1, 'Dawid', date '2026-10-16'),
  ('f1-preorder', 'task', 'launch', 'Google Play: przedrejestracja', 'Testy i wersje → Przedrejestracja. Opis: dokument „AudioKiddo w sklepach”.', 2, 'Dawid', date '2026-10-17'),
  ('f1-products', 'task', 'launch', 'Produkty i ceny w obu sklepach', 'Abonamenty z 7 dniami za darmo, pakiety, zestawy, zabawy. Identyfikatory dokładnie jak w docs/PUBLIKACJA.md, etap 6.', 1, 'Dawid', date '2026-10-17'),
  ('p-grudzien-0', 'task', 'pack', 'Pakiet „Święta z Szop’enem”: temat i lista 5 zabaw', 'Wybór na podstawie rankingu zabaw (CRM → Analiza) i pomysłów agenta.', 1, 'Razem', date '2026-10-19'),
  ('p-grudzien-1', 'task', 'launch', 'Pakiet „Święta z Szop’enem”: zgłoszenie do redakcji Apple (New Content)', 'App Store Connect → Featuring Nominations, 6 tygodni przed premierą pakietu.', 2, 'Nela', date '2026-10-19'),
  ('f1-diag', 'task', 'marketing', 'Diagnoza poprzedniej kampanii 2 000 zł i zakupu na telefonie', 'docs/STRATEGIA-5000-DO-MILIONA.md: co sprawdzić przed kolejną kampanią.', 2, 'Dawid', date '2026-10-20'),
  ('f1-social', 'task', 'marketing', 'Zapowiedź „wkrótce w App Store i Google Play”', 'Post, relacja i newsletter z linkiem do przedrejestracji Google. Pierwsza rolka z Szop’enem.', 2, 'Nela', date '2026-10-20'),
  ('f1-qa', 'task', 'launch', 'Test na telefonach: rejestracja, zakupy sandbox, odtwarzanie, mikrofon, tryb dziecka, widżet', 'Lista: docs/PUBLIKACJA.md, punkty 7.7–7.9.', 1, 'Razem', date '2026-10-21'),
  ('f1-video', 'task', 'marketing', 'Film podglądowy 30 s do obu sklepów', 'Dawid nagrywa ekran symulatora, Nela montuje i dodaje głos. Scenariusz: docs/sklepy/WYROZNIENIE.md, sekcja 7.', 2, 'Razem', date '2026-10-23'),
  ('f1-listing', 'task', 'launch', 'Karty w sklepach: zrzuty, opisy, prywatność, klasyfikacja, notatka dla recenzenta', 'Zrzuty: docs/sklepy/zrzuty/. Teksty: docs/SKLEPY.md i docs/sklepy/WYROZNIENIE.md.', 1, 'Dawid', date '2026-10-24'),
  ('f1-measure', 'task', 'marketing', 'Pomiar i maile: Pixel, Analytics, automatyzacje MailerLite', 'docs/REKLAMY.md, docs/marketing/NEWSLETTER.md i MAILE.md.', 2, 'Dawid', date '2026-10-25'),
  ('f1-submit', 'task', 'launch', 'iOS do recenzji Apple (wydanie ręczne)', 'Po zatwierdzeniu wersja czeka, aż sami ją opublikujemy (2.11).', 1, 'Dawid', date '2026-10-26'),
  ('p-grudzien-2', 'task', 'scenario', 'Pakiet „Święta z Szop’enem”: scenariusze', 'Agent pisze szkice (CRM → Pomysły → Napisz scenariusz zabawy), Nela poprawia.', 1, 'Nela', date '2026-10-26'),
  ('f1-nominate', 'task', 'launch', 'Zgłoszenie do redakcji Apple: New App Launch', 'App Store Connect → Featuring Nominations. Tekst: dokument „AudioKiddo w sklepach”. Data: 16.11.', 1, 'Nela', date '2026-10-27'),
  ('c-closed-end', 'calendar', 'launch', 'Koniec 14 dni testu zamkniętego Google', '', 2, 'Dawid', date '2026-10-30'),
  ('f2-android-prod', 'task', 'launch', 'Google: wniosek o dostęp do produkcji', 'Po 14 dniach testu zamkniętego: krótka ankieta o teście, potem wersja produkcyjna z wydaniem zarządzanym.', 1, 'Dawid', date '2026-10-31'),
  ('c-soft', 'calendar', 'update', 'Cicha publikacja iOS', '', 2, 'Dawid', date '2026-11-02'),
  ('f2-soft', 'task', 'launch', 'Cicha publikacja iOS (bez reklam)', 'Testerzy, rodzina i klienci instalują i oceniają. Cel: 20+ ocen przed premierą.', 1, 'Dawid', date '2026-11-02'),
  ('p-grudzien-3', 'task', 'pack', 'Pakiet „Święta z Szop’enem”: nagrania', '', 1, 'Nela', date '2026-11-02'),
  ('f2-b2b', 'task', 'marketing', 'Oferta dla 30 przedszkoli (kod na 30 dni)', 'docs/marketing/przedszkola/. Mail, telefon, potem spotkanie.', 3, 'Nela', date '2026-11-03'),
  ('f2-event-art', 'task', 'marketing', 'Grafiki: wydarzenia 1920×1080 (premiera, Święta), Google Play 1024×500', 'Claude może przygotować projekty z Szop’enem.', 2, 'Nela', date '2026-11-06'),
  ('f2-ratings', 'task', 'marketing', 'Prośba o ocenę do 50 znajomych rodziców i klientów', 'Link do sklepu i prośba o szczerą ocenę. Nagrody za ocenę są w sklepach zakazane.', 1, 'Nela', date '2026-11-06'),
  ('f2-reels', 'task', 'reel', 'Nagrać 4 rolki do premiery i reklam', 'docs/marketing/ROLKI-I-REKLAMY.md: Obiad, Podróż, Prawdziwa demonstracja, Szop’en.', 1, 'Nela', date '2026-11-06'),
  ('f2-influ', 'task', 'marketing', '10–15 mikroinfluencerek parentingowych: dostęp na 3 miesiące', 'Kody z tool/make_codes.py. Prośba o post lub rolkę 16–22.11, z oznaczeniem współpracy.', 2, 'Nela', date '2026-11-09'),
  ('f2-premiere-event', 'task', 'launch', 'Wydarzenie „Premiera” w App Store i promocja w Google Play', 'Apple sprawdza wydarzenia jak wersje, wysyłamy tydzień wcześniej.', 2, 'Dawid', date '2026-11-09'),
  ('p-grudzien-4', 'task', 'pack', 'Pakiet „Święta z Szop’enem”: montaż i okładka', '', 1, 'Nela', date '2026-11-09'),
  ('f2-gift', 'task', 'promotion', 'Prezent na Święta: produkty, kody, strona audiokiddo.pl/prezent', 'docs/marketing/PREZENT.md. Test zakupu i zwrotu.', 1, 'Dawid', date '2026-11-10'),
  ('f2-ads-setup', 'task', 'ad', 'Meta: transza 1 (1 500 zł) gotowa na 16.11', 'Jedna kampania sprzedażowa, 3–4 kreacje z rolek. docs/STRATEGIA-5000-DO-MILIONA.md.', 1, 'Dawid', date '2026-11-13'),
  ('f2-kpi', 'task', 'crm', 'KPI: zdarzenia z wersji sklepowej dochodzą do Studio', 'Serwer → KPI: True Activation, Free → Paid, D7.', 2, 'Dawid', date '2026-11-13'),
  ('f2-mail-premiere', 'task', 'newsletter', 'Newsletter premierowy zaplanowany na 16.11', 'Do subskrybentów i klientów sklepu: aplikacja w sklepach, 3 zabawy za darmo.', 1, 'Nela', date '2026-11-13'),
  ('c-premiere', 'calendar', 'release', 'PREMIERA w App Store i Google Play', '', 2, 'Razem', date '2026-11-16'),
  ('c-premiere-mail', 'calendar', 'newsletter', 'Newsletter premierowy', '', 2, 'Nela', date '2026-11-16'),
  ('f3-launch', 'task', 'launch', 'Premiera: publikacja w obu sklepach i start reklam', 'Android z wydania zarządzanego, iOS już w sklepie. Włączyć kampanię Meta.', 1, 'Dawid', date '2026-11-16'),
  ('f3-launch-social', 'task', 'post', 'Premiera w social media: post, rolka, relacje', '', 1, 'Nela', date '2026-11-16'),
  ('p-grudzien-5', 'task', 'pack', 'Pakiet „Święta z Szop’enem”: zabawy w Studio, produkt w obu sklepach', 'Studio → Treści; produkt jednorazowy w App Store Connect i Play Console.', 1, 'Dawid', date '2026-11-16'),
  ('f3-reviews', 'task', 'support', 'Odpowiadać na opinie w ciągu 24 h (CRM → Opinie)', 'Stałe zadanie od premiery. Agent pisze szkic, Nela poprawia i publikuje.', 2, 'Nela', date '2026-11-17'),
  ('f3-stability', 'task', 'server', 'Stabilność po premierze: CRM → Błędy, Xcode Organizer, Android Vitals', 'Cel: 99,5% sesji bez awarii.', 1, 'Dawid', date '2026-11-20'),
  ('f3-ads-check', 'task', 'ad', 'Meta po tygodniu: koszt pozyskania płacącego rodzica, decyzja o transzy 2', 'Zasady decyzji: docs/STRATEGIA-5000-DO-MILIONA.md.', 1, 'Dawid', date '2026-11-23'),
  ('p-grudzien-6', 'task', 'launch', 'Pakiet „Święta z Szop’enem”: wydarzenie w App Store i promocja w Google Play', '', 2, 'Dawid', date '2026-11-23'),
  ('p-grudzien-7', 'task', 'reel', 'Pakiet „Święta z Szop’enem”: rolka zapowiedź i grafika wydarzenia', '', 2, 'Nela', date '2026-11-23'),
  ('c-bf', 'calendar', 'promotion', 'Black Friday: prezent na audiokiddo.pl', '', 2, 'Razem', date '2026-11-27'),
  ('f3-bf', 'task', 'promotion', 'Black Friday: prezent na audiokiddo.pl', 'Zestaw 3 pakietów jako prezent. Bez obniżki abonamentu w aplikacji.', 2, 'Razem', date '2026-11-27'),
  ('c-pack-grudzien', 'calendar', 'release', 'Premiera pakietu „Święta z Szop’enem”', '', 2, 'Razem', date '2026-11-30'),
  ('p-grudzien-8', 'task', 'release', 'Pakiet „Święta z Szop’enem”: publikacja katalogu', 'Serwer → Katalog w aplikacji.', 1, 'Dawid', date '2026-11-30'),
  ('p-grudzien-9', 'task', 'newsletter', 'Pakiet „Święta z Szop’enem”: newsletter i posty', '', 2, 'Nela', date '2026-11-30'),
  ('p-styczen-0', 'task', 'pack', 'Pakiet „W drogę!”: temat i lista 5 zabaw', 'Wybór na podstawie rankingu zabaw (CRM → Analiza) i pomysłów agenta.', 1, 'Razem', date '2026-11-30'),
  ('p-styczen-1', 'task', 'launch', 'Pakiet „W drogę!”: zgłoszenie do redakcji Apple (New Content)', 'App Store Connect → Featuring Nominations, 6 tygodni przed premierą pakietu.', 2, 'Nela', date '2026-11-30'),
  ('f3-gift-campaign', 'task', 'promotion', 'Kampania prezentowa 1–20.12', 'Rolka „prezent dla wnuków”, newsletter, kartka do druku. docs/marketing/PREZENT.md.', 1, 'Nela', date '2026-12-01'),
  ('c-mikolajki', 'calendar', 'promotion', 'Mikołajki: ostatni dzień kampanii z kodem na Mikołajki', '', 2, 'Nela', date '2026-12-06'),
  ('f3-ab', 'task', 'launch', 'Test A/B pierwszego zrzutu w obu sklepach', '„Włącz, połóż telefon” kontra „Dziecko jest bohaterem przygody”. Wynik po 2–3 tygodniach.', 2, 'Dawid', date '2026-12-07'),
  ('p-grudzien-10', 'task', 'crm', 'Pakiet „Święta z Szop’enem”: przegląd liczb po tygodniu', 'Starty, ukończenia, powtórki, zakupy pakietu.', 2, 'Razem', date '2026-12-07'),
  ('p-styczen-2', 'task', 'scenario', 'Pakiet „W drogę!”: scenariusze', 'Agent pisze szkice (CRM → Pomysły → Napisz scenariusz zabawy), Nela poprawia.', 1, 'Nela', date '2026-12-07'),
  ('p-styczen-3', 'task', 'pack', 'Pakiet „W drogę!”: nagrania', '', 1, 'Nela', date '2026-12-14'),
  ('c-gift-last', 'calendar', 'promotion', 'Ostatni dzień prezentów na Święta (kod mailem)', '', 2, 'Nela', date '2026-12-20'),
  ('p-luty-0', 'task', 'pack', 'Pakiet „Spokojnie na dobranoc”: temat i lista 5 zabaw', 'Wybór na podstawie rankingu zabaw (CRM → Analiza) i pomysłów agenta.', 1, 'Razem', date '2026-12-21'),
  ('p-luty-1', 'task', 'launch', 'Pakiet „Spokojnie na dobranoc”: zgłoszenie do redakcji Apple (New Content)', 'App Store Connect → Featuring Nominations, 6 tygodni przed premierą pakietu.', 2, 'Nela', date '2026-12-21'),
  ('p-styczen-4', 'task', 'pack', 'Pakiet „W drogę!”: montaż i okładka', '', 1, 'Nela', date '2026-12-21'),
  ('f3-year', 'task', 'crm', 'Podsumowanie roku i plan na I kwartał', 'Liczby z CRM, co działa, co wyłączamy, budżet reklam na ferie.', 2, 'Razem', date '2026-12-28'),
  ('p-luty-2', 'task', 'scenario', 'Pakiet „Spokojnie na dobranoc”: scenariusze', 'Agent pisze szkice (CRM → Pomysły → Napisz scenariusz zabawy), Nela poprawia.', 1, 'Nela', date '2026-12-28'),
  ('p-styczen-5', 'task', 'pack', 'Pakiet „W drogę!”: zabawy w Studio, produkt w obu sklepach', 'Studio → Treści; produkt jednorazowy w App Store Connect i Play Console.', 1, 'Dawid', date '2026-12-28'),
  ('p-luty-3', 'task', 'pack', 'Pakiet „Spokojnie na dobranoc”: nagrania', '', 1, 'Nela', date '2027-01-04'),
  ('p-styczen-6', 'task', 'launch', 'Pakiet „W drogę!”: wydarzenie w App Store i promocja w Google Play', '', 2, 'Dawid', date '2027-01-04'),
  ('p-styczen-7', 'task', 'reel', 'Pakiet „W drogę!”: rolka zapowiedź i grafika wydarzenia', '', 2, 'Nela', date '2027-01-04'),
  ('c-pack-styczen', 'calendar', 'release', 'Premiera pakietu „W drogę!”', '', 2, 'Razem', date '2027-01-11'),
  ('f4-ads-scale', 'task', 'ad', 'Ferie: zwiększyć budżet tylko na kreacje z kosztem pozyskania poniżej progu', 'Zwiększamy stopniowo, po 20–30 opłaconych zamówieniach.', 1, 'Dawid', date '2027-01-11'),
  ('p-luty-4', 'task', 'pack', 'Pakiet „Spokojnie na dobranoc”: montaż i okładka', '', 1, 'Nela', date '2027-01-11'),
  ('p-styczen-8', 'task', 'release', 'Pakiet „W drogę!”: publikacja katalogu', 'Serwer → Katalog w aplikacji.', 1, 'Dawid', date '2027-01-11'),
  ('p-styczen-9', 'task', 'newsletter', 'Pakiet „W drogę!”: newsletter i posty', '', 2, 'Nela', date '2027-01-11'),
  ('f4-teacher', 'task', 'launch', 'Google Play: status Teacher Approved i wymagania Families', 'Play Console → Treści aplikacji → Grupa docelowa.', 3, 'Dawid', date '2027-01-15'),
  ('c-ferie', 'calendar', 'promotion', 'Start ferii zimowych (pierwsze województwa)', '', 2, 'Razem', date '2027-01-18'),
  ('p-luty-5', 'task', 'pack', 'Pakiet „Spokojnie na dobranoc”: zabawy w Studio, produkt w obu sklepach', 'Studio → Treści; produkt jednorazowy w App Store Connect i Play Console.', 1, 'Dawid', date '2027-01-18'),
  ('p-marzec-0', 'task', 'pack', 'Pakiet „Wiosenni odkrywcy”: temat i lista 5 zabaw', 'Wybór na podstawie rankingu zabaw (CRM → Analiza) i pomysłów agenta.', 1, 'Razem', date '2027-01-18'),
  ('p-marzec-1', 'task', 'launch', 'Pakiet „Wiosenni odkrywcy”: zgłoszenie do redakcji Apple (New Content)', 'App Store Connect → Featuring Nominations, 6 tygodni przed premierą pakietu.', 2, 'Nela', date '2027-01-18'),
  ('p-styczen-10', 'task', 'crm', 'Pakiet „W drogę!”: przegląd liczb po tygodniu', 'Starty, ukończenia, powtórki, zakupy pakietu.', 2, 'Razem', date '2027-01-18'),
  ('p-luty-6', 'task', 'launch', 'Pakiet „Spokojnie na dobranoc”: wydarzenie w App Store i promocja w Google Play', '', 2, 'Dawid', date '2027-01-25'),
  ('p-luty-7', 'task', 'reel', 'Pakiet „Spokojnie na dobranoc”: rolka zapowiedź i grafika wydarzenia', '', 2, 'Nela', date '2027-01-25'),
  ('p-marzec-2', 'task', 'scenario', 'Pakiet „Wiosenni odkrywcy”: scenariusze', 'Agent pisze szkice (CRM → Pomysły → Napisz scenariusz zabawy), Nela poprawia.', 1, 'Nela', date '2027-01-25'),
  ('c-pack-luty', 'calendar', 'release', 'Premiera pakietu „Spokojnie na dobranoc”', '', 2, 'Razem', date '2027-02-01'),
  ('p-luty-8', 'task', 'release', 'Pakiet „Spokojnie na dobranoc”: publikacja katalogu', 'Serwer → Katalog w aplikacji.', 1, 'Dawid', date '2027-02-01'),
  ('p-luty-9', 'task', 'newsletter', 'Pakiet „Spokojnie na dobranoc”: newsletter i posty', '', 2, 'Nela', date '2027-02-01'),
  ('p-marzec-3', 'task', 'pack', 'Pakiet „Wiosenni odkrywcy”: nagrania', '', 1, 'Nela', date '2027-02-01'),
  ('p-luty-10', 'task', 'crm', 'Pakiet „Spokojnie na dobranoc”: przegląd liczb po tygodniu', 'Starty, ukończenia, powtórki, zakupy pakietu.', 2, 'Razem', date '2027-02-08'),
  ('p-marzec-4', 'task', 'pack', 'Pakiet „Wiosenni odkrywcy”: montaż i okładka', '', 1, 'Nela', date '2027-02-08'),
  ('f4-b2b2', 'task', 'marketing', 'Przedszkola: decyzje po 30 dniach i kolejna fala ofert', '', 3, 'Nela', date '2027-02-15'),
  ('p-marzec-5', 'task', 'pack', 'Pakiet „Wiosenni odkrywcy”: zabawy w Studio, produkt w obu sklepach', 'Studio → Treści; produkt jednorazowy w App Store Connect i Play Console.', 1, 'Dawid', date '2027-02-15'),
  ('p-kwiecien-0', 'task', 'pack', 'Pakiet „Detektyw: nowe sprawy”: temat i lista 5 zabaw', 'Wybór na podstawie rankingu zabaw (CRM → Analiza) i pomysłów agenta.', 1, 'Razem', date '2027-02-22'),
  ('p-kwiecien-1', 'task', 'launch', 'Pakiet „Detektyw: nowe sprawy”: zgłoszenie do redakcji Apple (New Content)', 'App Store Connect → Featuring Nominations, 6 tygodni przed premierą pakietu.', 2, 'Nela', date '2027-02-22'),
  ('p-marzec-6', 'task', 'launch', 'Pakiet „Wiosenni odkrywcy”: wydarzenie w App Store i promocja w Google Play', '', 2, 'Dawid', date '2027-02-22'),
  ('p-marzec-7', 'task', 'reel', 'Pakiet „Wiosenni odkrywcy”: rolka zapowiedź i grafika wydarzenia', '', 2, 'Nela', date '2027-02-22'),
  ('c-pack-marzec', 'calendar', 'release', 'Premiera pakietu „Wiosenni odkrywcy”', '', 2, 'Razem', date '2027-03-01'),
  ('p-kwiecien-2', 'task', 'scenario', 'Pakiet „Detektyw: nowe sprawy”: scenariusze', 'Agent pisze szkice (CRM → Pomysły → Napisz scenariusz zabawy), Nela poprawia.', 1, 'Nela', date '2027-03-01'),
  ('p-marzec-8', 'task', 'release', 'Pakiet „Wiosenni odkrywcy”: publikacja katalogu', 'Serwer → Katalog w aplikacji.', 1, 'Dawid', date '2027-03-01'),
  ('p-marzec-9', 'task', 'newsletter', 'Pakiet „Wiosenni odkrywcy”: newsletter i posty', '', 2, 'Nela', date '2027-03-01'),
  ('p-kwiecien-3', 'task', 'pack', 'Pakiet „Detektyw: nowe sprawy”: nagrania', '', 1, 'Nela', date '2027-03-08'),
  ('p-marzec-10', 'task', 'crm', 'Pakiet „Wiosenni odkrywcy”: przegląd liczb po tygodniu', 'Starty, ukończenia, powtórki, zakupy pakietu.', 2, 'Razem', date '2027-03-08'),
  ('p-kwiecien-4', 'task', 'pack', 'Pakiet „Detektyw: nowe sprawy”: montaż i okładka', '', 1, 'Nela', date '2027-03-15'),
  ('p-kwiecien-5', 'task', 'pack', 'Pakiet „Detektyw: nowe sprawy”: zabawy w Studio, produkt w obu sklepach', 'Studio → Treści; produkt jednorazowy w App Store Connect i Play Console.', 1, 'Dawid', date '2027-03-22'),
  ('p-kwiecien-6', 'task', 'launch', 'Pakiet „Detektyw: nowe sprawy”: wydarzenie w App Store i promocja w Google Play', '', 2, 'Dawid', date '2027-03-29'),
  ('p-kwiecien-7', 'task', 'reel', 'Pakiet „Detektyw: nowe sprawy”: rolka zapowiedź i grafika wydarzenia', '', 2, 'Nela', date '2027-03-29'),
  ('c-pack-kwiecien', 'calendar', 'release', 'Premiera pakietu „Detektyw: nowe sprawy”', '', 2, 'Razem', date '2027-04-05'),
  ('p-kwiecien-8', 'task', 'release', 'Pakiet „Detektyw: nowe sprawy”: publikacja katalogu', 'Serwer → Katalog w aplikacji.', 1, 'Dawid', date '2027-04-05'),
  ('p-kwiecien-9', 'task', 'newsletter', 'Pakiet „Detektyw: nowe sprawy”: newsletter i posty', '', 2, 'Nela', date '2027-04-05'),
  ('p-kwiecien-10', 'task', 'crm', 'Pakiet „Detektyw: nowe sprawy”: przegląd liczb po tygodniu', 'Starty, ukończenia, powtórki, zakupy pakietu.', 2, 'Razem', date '2027-04-12'),
  ('p-maj-0', 'task', 'pack', 'Pakiet „Wielka przygoda na Dzień Dziecka”: temat i lista 5 zabaw', 'Wybór na podstawie rankingu zabaw (CRM → Analiza) i pomysłów agenta.', 1, 'Razem', date '2027-04-12'),
  ('p-maj-1', 'task', 'launch', 'Pakiet „Wielka przygoda na Dzień Dziecka”: zgłoszenie do redakcji Apple (New Content)', 'App Store Connect → Featuring Nominations, 6 tygodni przed premierą pakietu.', 2, 'Nela', date '2027-04-12'),
  ('p-maj-2', 'task', 'scenario', 'Pakiet „Wielka przygoda na Dzień Dziecka”: scenariusze', 'Agent pisze szkice (CRM → Pomysły → Napisz scenariusz zabawy), Nela poprawia.', 1, 'Nela', date '2027-04-19'),
  ('p-maj-3', 'task', 'pack', 'Pakiet „Wielka przygoda na Dzień Dziecka”: nagrania', '', 1, 'Nela', date '2027-04-26'),
  ('p-maj-4', 'task', 'pack', 'Pakiet „Wielka przygoda na Dzień Dziecka”: montaż i okładka', '', 1, 'Nela', date '2027-05-03'),
  ('p-maj-5', 'task', 'pack', 'Pakiet „Wielka przygoda na Dzień Dziecka”: zabawy w Studio, produkt w obu sklepach', 'Studio → Treści; produkt jednorazowy w App Store Connect i Play Console.', 1, 'Dawid', date '2027-05-10'),
  ('p-maj-6', 'task', 'launch', 'Pakiet „Wielka przygoda na Dzień Dziecka”: wydarzenie w App Store i promocja w Google Play', '', 2, 'Dawid', date '2027-05-17'),
  ('p-maj-7', 'task', 'reel', 'Pakiet „Wielka przygoda na Dzień Dziecka”: rolka zapowiedź i grafika wydarzenia', '', 2, 'Nela', date '2027-05-17'),
  ('c-pack-maj', 'calendar', 'release', 'Premiera pakietu „Wielka przygoda na Dzień Dziecka”', '', 2, 'Razem', date '2027-05-24'),
  ('p-maj-8', 'task', 'release', 'Pakiet „Wielka przygoda na Dzień Dziecka”: publikacja katalogu', 'Serwer → Katalog w aplikacji.', 1, 'Dawid', date '2027-05-24'),
  ('p-maj-9', 'task', 'newsletter', 'Pakiet „Wielka przygoda na Dzień Dziecka”: newsletter i posty', '', 2, 'Nela', date '2027-05-24'),
  ('p-maj-10', 'task', 'crm', 'Pakiet „Wielka przygoda na Dzień Dziecka”: przegląd liczb po tygodniu', 'Starty, ukończenia, powtórki, zakupy pakietu.', 2, 'Razem', date '2027-05-31'),
  ('c-dd', 'calendar', 'promotion', 'Dzień Dziecka', '', 2, 'Razem', date '2027-06-01'),
  ('f4-dd-week', 'task', 'promotion', 'Tydzień Dnia Dziecka: wydarzenie, newsletter, rolka, naklejki', '', 1, 'Razem', date '2027-06-01'),
  ('f4-half', 'task', 'crm', 'Przegląd półrocza: cel 1 000 subskrypcji, decyzja o wersji angielskiej', '', 2, 'Razem', date '2027-06-30')
) as v(key, kind, area, title, body, priority, owner, due)
where not exists (
  select 1 from public.crm_items c where c.data->>'plan' = 'premiera-2026' and c.data->>'key' = v.key
);
