-- The faster launch plan (8 October, evening): Dawid works 8 hours a day including weekends, and
-- Pixel and Analytics are already in the CRM. iOS goes public as soon as Apple approves it
-- (about 15 October), Android after Google's 14-day closed test (about 29 October), and the
-- premiere with ads, newsletter and influencers moves from 16 to 2 November.
-- Only what is still as the plan wrote it changes: a task moved, renamed or reworded on the
-- board keeps its own date and words.

update public.crm_items c
set due = case when c.due = v.old_due then v.new_due else c.due end,
    title = case when c.title = v.old_title then v.new_title else c.title end,
    body = case when v.old_body <> '' and position(v.old_body in c.body) = 1
                then v.new_body || substr(c.body, length(v.old_body) + 1) else c.body end
from (values
  ('f1-deploy', date '2026-10-12', date '2026-10-09', 'Wgrać zaległe zmiany na serwer', 'Wgrać zaległe zmiany na serwer', 'supabase db push, supabase functions deploy (admin, woo-webhook), sekrety prezentów. docs/PUBLIKACJA.md, etap 1.', 'supabase db push, supabase functions deploy (admin, woo-webhook), sekrety prezentów. docs/PUBLIKACJA.md, etap 1.'),
  ('f1-decisions', date '2026-10-12', date '2026-10-10', 'Decyzje: Kids 6–8 lat, ceny planów rodzinnych, premiera 16.11', 'Decyzje: Kids 6–8 lat, ceny planów rodzinnych, premiera 2.11', 'Szczegóły: dokument „AudioKiddo w sklepach”, sekcja Decyzje.', 'Szczegóły: dokument „AudioKiddo w sklepach”, sekcja Decyzje.'),
  ('f1-invite', date '2026-10-12', date '2026-10-10', 'Dodać Dawida jako administratora w App Store Connect i Play Console', 'Dodać Dawida jako administratora w App Store Connect i Play Console', '', ''),
  ('f1-pages', date '2026-10-13', date '2026-10-09', 'Strony na audiokiddo.pl: polityka, kontakt, usuwanie konta, regulamin', 'Strony na audiokiddo.pl: polityka, kontakt, usuwanie konta, regulamin', 'Kod w docs/strona/sklepy/. Sklepy nie przyjmą aplikacji bez tych adresów. docs/PUBLIKACJA.md, etap 3.', 'Kod w docs/strona/sklepy/. Sklepy nie przyjmą aplikacji bez tych adresów. docs/PUBLIKACJA.md, etap 3.'),
  ('f1-testers', date '2026-10-14', date '2026-10-10', 'Zebrać 16–18 testerów Androida (adresy Gmail)', 'Zebrać 16–18 testerów Androida (adresy Gmail)', 'Znajomi rodzice, rodzina, klienci z Empiku i sklepu. Wiadomość: docs/marketing/SKLEPY-SZYBKA-SCIEZKA.md. Każdy dostaje kod na 90 dni.', 'Znajomi rodzice, rodzina, klienci z Empiku i sklepu. Każdy dzień zwłoki to dzień później na Androidzie: test 14 dni rusza, gdy 12 osób ma aplikację. Wiadomość: docs/marketing/PREMIERA-TEKSTY.md. Każdy dostaje kod na 90 dni.'),
  ('f1-business', date '2026-10-14', date '2026-10-10', 'Umowy i wypłaty: Paid Apps, konto bankowe, W-8BEN, profil płatności Google', 'Umowy i wypłaty: Paid Apps, konto bankowe, W-8BEN, profil płatności Google', 'Bez tego zakupy nie działają nawet w testach. Robi właścicielka konta.', 'Bez tego zakupy nie działają nawet w testach. Robi właścicielka konta.'),
  ('f1-apple-setup', date '2026-10-15', date '2026-10-10', 'Apple: identyfikatory, App Group, aplikacja w App Store Connect, podpisywanie', 'Apple: identyfikatory, App Group, aplikacja w App Store Connect, podpisywanie', 'docs/PUBLIKACJA.md, etap 4.', 'docs/PUBLIKACJA.md, etap 4. Gdy tylko przyjdzie mail „Welcome to the Apple Developer Program”.'),
  ('f1-android-key', date '2026-10-15', date '2026-10-09', 'Android: klucz przesyłania, key.properties i kopia zapasowa', 'Android: klucz przesyłania, key.properties i kopia zapasowa', 'docs/PUBLIKACJA.md, etap 5.', 'docs/PUBLIKACJA.md, etap 5.'),
  ('f1-testflight', date '2026-10-16', date '2026-10-10', 'Pierwsza wersja w TestFlight i w teście wewnętrznym Google', 'Pierwsza wersja w TestFlight i w teście wewnętrznym Google', 'tool/release_build.sh ios / android. docs/PUBLIKACJA.md, etap 7.', 'tool/release_build.sh ios / android. docs/PUBLIKACJA.md, etap 7.'),
  ('f1-closed', date '2026-10-16', date '2026-10-11', 'Google: test zamknięty z 12+ testerami', 'Google: test zamknięty z 12+ testerami', 'Testowanie → Testy zamknięte. 14 dni bez przerwy liczy się od dnia, w którym 12 osób ma aplikację. Koniec ok. 30.10.', 'Testowanie → Testy zamknięte. 14 dni bez przerwy liczy się od dnia, w którym 12 osób ma aplikację. Koniec ok. 26.10.'),
  ('f1-products', date '2026-10-17', date '2026-10-11', 'Produkty i ceny w obu sklepach', 'Produkty i ceny w obu sklepach', 'Abonamenty z 7 dniami za darmo, pakiety, zestawy, zabawy. Identyfikatory dokładnie jak w docs/PUBLIKACJA.md, etap 6.', 'Abonamenty z 7 dniami za darmo, pakiety, zestawy, zabawy. Identyfikatory dokładnie jak w docs/PUBLIKACJA.md, etap 6.'),
  ('f1-preorder', date '2026-10-17', date '2026-10-11', 'Google Play: przedrejestracja', 'Google Play: przedrejestracja', 'Testy i wersje → Przedrejestracja. Opis: dokument „AudioKiddo w sklepach”.', 'Testy i wersje → Przedrejestracja. Opis: dokument „AudioKiddo w sklepach”.'),
  ('f1-social', date '2026-10-20', date '2026-10-13', 'Zapowiedź „wkrótce w App Store i Google Play”', 'Zapowiedź „wkrótce w App Store i Google Play”', 'Post, relacja i newsletter z linkiem do przedrejestracji Google. Pierwsza rolka z Szop’enem.', 'Post, relacja i newsletter z linkiem do przedrejestracji Google. Pierwsza rolka z Szop’enem.'),
  ('f1-diag', date '2026-10-20', date '2026-10-09', 'Diagnoza poprzedniej kampanii 2 000 zł i zakupu na telefonie', 'Diagnoza poprzedniej kampanii 2 000 zł i zakupu na telefonie', 'docs/STRATEGIA-5000-DO-MILIONA.md: co sprawdzić przed kolejną kampanią.', 'docs/STRATEGIA-5000-DO-MILIONA.md: co sprawdzić przed kolejną kampanią.'),
  ('f1-qa', date '2026-10-21', date '2026-10-11', 'Test na telefonach: rejestracja, zakupy sandbox, odtwarzanie, mikrofon, tryb dziecka, widżet', 'Test na telefonach: rejestracja, zakupy sandbox, odtwarzanie, mikrofon, tryb dziecka, widżet', 'Lista: docs/PUBLIKACJA.md, punkty 7.7–7.9.', 'Lista: docs/PUBLIKACJA.md, punkty 7.7–7.9.'),
  ('f1-video', date '2026-10-23', date '2026-10-12', 'Film podglądowy 30 s do obu sklepów', 'Film podglądowy 30 s do obu sklepów', 'Dawid nagrywa ekran symulatora, Nela montuje i dodaje głos. Scenariusz: docs/sklepy/WYROZNIENIE.md, sekcja 7.', 'Dawid nagrywa ekran symulatora, Nela montuje i dodaje głos. Scenariusz: docs/sklepy/WYROZNIENIE.md, sekcja 7.'),
  ('f1-listing', date '2026-10-24', date '2026-10-10', 'Karty w sklepach: zrzuty, opisy, prywatność, klasyfikacja, notatka dla recenzenta', 'Karty w sklepach: zrzuty, opisy, prywatność, klasyfikacja, notatka dla recenzenta', 'Zrzuty: docs/sklepy/zrzuty/. Teksty: docs/SKLEPY.md i docs/sklepy/WYROZNIENIE.md.', 'Zrzuty: docs/sklepy/zrzuty/. Teksty: docs/SKLEPY.md i docs/sklepy/WYROZNIENIE.md.'),
  ('f1-measure', date '2026-10-25', date '2026-10-09', 'Pomiar i maile: Pixel, Analytics, automatyzacje MailerLite', 'Maile: automatyzacje MailerLite (Pixel i Analytics już są w CRM)', 'docs/REKLAMY.md, docs/marketing/NEWSLETTER.md i MAILE.md.', 'docs/marketing/NEWSLETTER.md i MAILE.md.'),
  ('f1-submit', date '2026-10-26', date '2026-10-12', 'iOS do recenzji Apple (wydanie ręczne)', 'iOS do recenzji Apple (wydanie po zatwierdzeniu)', 'Po zatwierdzeniu wersja czeka, aż sami ją opublikujemy (2.11).', 'Recenzja trwa zwykle 1–3 dni. Po zatwierdzeniu publikujemy od razu, bez reklam: zbieramy pierwsze oceny.'),
  ('f1-nominate', date '2026-10-27', date '2026-10-12', 'Zgłoszenie do redakcji Apple: New App Launch', 'Zgłoszenie do redakcji Apple: New App Launch', 'App Store Connect → Featuring Nominations. Tekst: dokument „AudioKiddo w sklepach”. Data: 16.11.', 'App Store Connect → Featuring Nominations. Tekst: dokument „AudioKiddo w sklepach”. Data premiery: 2.11.'),
  ('f2-android-prod', date '2026-10-31', date '2026-10-26', 'Google: wniosek o dostęp do produkcji', 'Google: wniosek o dostęp do produkcji', 'Po 14 dniach testu zamkniętego: krótka ankieta o teście, potem wersja produkcyjna z wydaniem zarządzanym.', 'Po 14 dniach testu zamkniętego: krótka ankieta o teście, potem wersja produkcyjna z wydaniem zarządzanym.'),
  ('f2-soft', date '2026-11-02', date '2026-10-15', 'Cicha publikacja iOS (bez reklam)', 'Publikacja iOS po zatwierdzeniu (bez reklam)', 'Testerzy, rodzina i klienci instalują i oceniają. Cel: 20+ ocen przed premierą.', 'Testerzy, rodzina i klienci instalują i oceniają. Cel: 20+ ocen przed premierą 2.11.'),
  ('f2-b2b', date '2026-11-03', date '2026-11-04', 'Oferta dla 30 przedszkoli (kod na 30 dni)', 'Oferta dla 30 przedszkoli (kod na 30 dni)', 'docs/marketing/przedszkola/. Mail, telefon, potem spotkanie.', 'docs/marketing/przedszkola/. Mail, telefon, potem spotkanie.'),
  ('f2-ratings', date '2026-11-06', date '2026-10-17', 'Prośba o ocenę do 50 znajomych rodziców i klientów', 'Prośba o ocenę do 50 znajomych rodziców i klientów', 'Link do sklepu i prośba o szczerą ocenę. Nagrody za ocenę są w sklepach zakazane.', 'Link do sklepu i prośba o szczerą ocenę. Nagrody za ocenę są w sklepach zakazane.'),
  ('f2-reels', date '2026-11-06', date '2026-10-28', 'Nagrać 4 rolki do premiery i reklam', 'Nagrać 4 rolki do premiery i reklam', 'docs/marketing/ROLKI-I-REKLAMY.md: Obiad, Podróż, Prawdziwa demonstracja, Szop’en.', 'docs/marketing/ROLKI-I-REKLAMY.md: Obiad, Podróż, Prawdziwa demonstracja, Szop’en. Montaż może przejąć Dawid.'),
  ('f2-event-art', date '2026-11-06', date '2026-10-24', 'Grafiki: wydarzenia 1920×1080 (premiera, Święta), Google Play 1024×500', 'Grafiki: wydarzenia 1920×1080 (premiera, Święta), Google Play 1024×500', 'Claude może przygotować projekty z Szop’enem.', 'Claude może przygotować projekty z Szop’enem.'),
  ('f2-premiere-event', date '2026-11-09', date '2026-10-26', 'Wydarzenie „Premiera” w App Store i promocja w Google Play', 'Wydarzenie „Premiera” w App Store i promocja w Google Play', 'Apple sprawdza wydarzenia jak wersje, wysyłamy tydzień wcześniej.', 'Apple sprawdza wydarzenia jak wersje, wysyłamy tydzień wcześniej.'),
  ('f2-influ', date '2026-11-09', date '2026-10-26', '10–15 mikroinfluencerek parentingowych: dostęp na 3 miesiące', '10–15 mikroinfluencerek parentingowych: dostęp na 3 miesiące', 'Kody z tool/make_codes.py. Prośba o post lub rolkę 16–22.11, z oznaczeniem współpracy.', 'Kody z tool/make_codes.py. Prośba o post lub rolkę 2–8.11, z oznaczeniem współpracy.'),
  ('f2-gift', date '2026-11-10', date '2026-10-14', 'Prezent na Święta: produkty, kody, strona audiokiddo.pl/prezent', 'Prezent na Święta: produkty, kody, strona audiokiddo.pl/prezent', 'docs/marketing/PREZENT.md. Test zakupu i zwrotu.', 'docs/marketing/PREZENT.md. Test zakupu i zwrotu.'),
  ('f2-ads-setup', date '2026-11-13', date '2026-10-30', 'Meta: transza 1 (1 500 zł) gotowa na 16.11', 'Meta: transza 1 (1 500 zł) gotowa na 2.11', 'Jedna kampania sprzedażowa, 3–4 kreacje z rolek. docs/STRATEGIA-5000-DO-MILIONA.md.', 'Jedna kampania sprzedażowa, 3–4 kreacje z rolek. docs/STRATEGIA-5000-DO-MILIONA.md.'),
  ('f2-kpi', date '2026-11-13', date '2026-10-16', 'KPI: zdarzenia z wersji sklepowej dochodzą do Studio', 'KPI: zdarzenia z wersji sklepowej dochodzą do Studio', 'Serwer → KPI: True Activation, Free → Paid, D7.', 'Serwer → KPI: True Activation, Free → Paid, D7.'),
  ('f2-mail-premiere', date '2026-11-13', date '2026-10-30', 'Newsletter premierowy zaplanowany na 16.11', 'Newsletter premierowy zaplanowany na 2.11', 'Do subskrybentów i klientów sklepu: aplikacja w sklepach, 3 zabawy za darmo.', 'Do subskrybentów i klientów sklepu: aplikacja w sklepach, 3 zabawy za darmo.'),
  ('f3-launch', date '2026-11-16', date '2026-11-02', 'Premiera: publikacja w obu sklepach i start reklam', 'Premiera: Android w sklepie, start reklam', 'Android z wydania zarządzanego, iOS już w sklepie. Włączyć kampanię Meta.', 'iOS jest już w sklepie od ok. 15.10. Włączyć kampanię Meta.'),
  ('f3-launch-social', date '2026-11-16', date '2026-11-02', 'Premiera w social media: post, rolka, relacje', 'Premiera w social media: post, rolka, relacje', '', ''),
  ('f3-reviews', date '2026-11-17', date '2026-10-16', 'Odpowiadać na opinie w ciągu 24 h (CRM → Opinie)', 'Odpowiadać na opinie w ciągu 24 h (CRM → Opinie)', 'Stałe zadanie od premiery. Agent pisze szkic, Nela poprawia i publikuje.', 'Stałe zadanie od publikacji iOS. Agent pisze szkic, Nela poprawia i publikuje.'),
  ('f3-stability', date '2026-11-20', date '2026-11-06', 'Stabilność po premierze: CRM → Błędy, Xcode Organizer, Android Vitals', 'Stabilność po premierze: CRM → Błędy, Xcode Organizer, Android Vitals', 'Cel: 99,5% sesji bez awarii.', 'Cel: 99,5% sesji bez awarii.'),
  ('f3-ads-check', date '2026-11-23', date '2026-11-09', 'Meta po tygodniu: koszt pozyskania płacącego rodzica, decyzja o transzy 2', 'Meta po tygodniu: koszt pozyskania płacącego rodzica, decyzja o transzy 2', 'Zasady decyzji: docs/STRATEGIA-5000-DO-MILIONA.md.', 'Zasady decyzji: docs/STRATEGIA-5000-DO-MILIONA.md.'),
  ('f3-ab', date '2026-12-07', date '2026-11-23', 'Test A/B pierwszego zrzutu w obu sklepach', 'Test A/B pierwszego zrzutu w obu sklepach', '„Włącz, połóż telefon” kontra „Dziecko jest bohaterem przygody”. Wynik po 2–3 tygodniach.', '„Włącz, połóż telefon” kontra „Dziecko jest bohaterem przygody”. Wynik po 2–3 tygodniach.'),
  ('c-closed-end', date '2026-10-30', date '2026-10-26', 'Koniec 14 dni testu zamkniętego Google', 'Koniec 14 dni testu zamkniętego Google', '', ''),
  ('c-soft', date '2026-11-02', date '2026-10-15', 'Cicha publikacja iOS', 'Publikacja iOS (po zatwierdzeniu)', '', ''),
  ('c-premiere', date '2026-11-16', date '2026-11-02', 'PREMIERA w App Store i Google Play', 'PREMIERA w App Store i Google Play', '', ''),
  ('c-premiere-mail', date '2026-11-16', date '2026-11-02', 'Newsletter premierowy', 'Newsletter premierowy', '', '')
) as v(key, old_due, new_due, old_title, new_title, old_body, new_body)
where c.data->>'plan' = 'premiera-2026' and c.data->>'key' = v.key;

-- Pixel and Analytics are done: the measuring task is only the MailerLite automations now.
update public.crm_items
set data = data || '{"hours": 1.5}', body = replace(body, 'Czas: ok. 3 h.', 'Czas: ok. 1,5 h.')
where data->>'plan' = 'premiera-2026' and data->>'key' = 'f1-measure';
