-- Audit 2026-09-28, P1-6: paid recordings are served only through short-lived signed links
-- (download-url function + tool/lhpl/get.php). This table says which item a file belongs to
-- and whether it is free; can_download() applies the same rules as the app's access policy.

create table public.content_files (
  path text primary key check (path !~ '(^/|\.\.)'),
  item_id text not null,
  pack_id text,
  free boolean not null default false
);

alter table public.content_files enable row level security;
-- No policies: only the service role (download-url) reads it.

create or replace function public.can_download(p_user_id uuid, p_path text)
returns boolean language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from public.content_files f
    where f.path = p_path
      and (
        f.free
        or exists (
          select 1 from public.entitlements e
          where e.user_id = p_user_id
            and e.status in ('active', 'grace')
            and (e.valid_until is null or e.valid_until > now())
            and (e.scope = 'all_content' or e.scope = 'item:' || f.item_id or e.scope = 'pack:' || f.pack_id)
        )
      )
  )
$$;

revoke all on function public.can_download(uuid, text) from public, anon, authenticated;
grant execute on function public.can_download(uuid, text) to service_role;
grant select on public.content_files to service_role;

-- Generated by tool/content_files_sql.py from app/assets/mock/catalog.json.
insert into public.content_files (path, item_id, pack_id, free) values
  ('audio/detektyw/gadajacy-smietnik.m4a', 'gadajacy-smietnik', 'detektyw', false),
  ('audio/detektyw/na-ratunek-budce-z-lodami.m4a', 'na-ratunek-budce-z-lodami', 'detektyw', false),
  ('audio/detektyw/tajemnicze-znaki.m4a', 'tajemnicze-znaki', 'detektyw', false),
  ('audio/detektyw/zlodziej-naszyjnika.m4a', 'zlodziej-naszyjnika', 'detektyw', true),
  ('audio/detektyw/znikajace-dzwonki.m4a', 'znikajace-dzwonki', 'detektyw', false),
  ('audio/piosenki/1.m4a', 'piosenka-1', null, false),
  ('audio/piosenki/2.m4a', 'piosenka-2', null, false),
  ('audio/piosenki/3.m4a', 'piosenka-3', null, false),
  ('audio/slowa-i-wiedza/co-to-za-dzwiek.m4a', 'co-to-za-dzwiek', 'slowa-i-wiedza', true),
  ('audio/slowa-i-wiedza/co-to-za-przedmiot.m4a', 'co-to-za-przedmiot', 'slowa-i-wiedza', false),
  ('audio/slowa-i-wiedza/co-tu-nie-pasuje.m4a', 'co-tu-nie-pasuje', 'slowa-i-wiedza', false),
  ('audio/slowa-i-wiedza/dokoncz-zgodnie-z-prawda.m4a', 'dokoncz-zgodnie-z-prawda', 'slowa-i-wiedza', false),
  ('audio/slowa-i-wiedza/kto-to-powiedzial.m4a', 'kto-to-powiedzial', 'slowa-i-wiedza', false),
  ('audio/slowa-i-wiedza/szybkie-skojarzenia.m4a', 'szybkie-skojarzenia', 'slowa-i-wiedza', false),
  ('audio/slowa-i-wiedza/uloz-zdanie.m4a', 'uloz-zdanie', 'slowa-i-wiedza', false),
  ('audio/slowa-i-wiedza/wymien-trzy.m4a', 'wymien-trzy', 'slowa-i-wiedza', false),
  ('audio/slowa-i-wiedza/znajdz-przeciwienstwo.m4a', 'znajdz-przeciwienstwo', 'slowa-i-wiedza', false),
  ('audio/slowa-i-wiedza/znajdz-synonimy.m4a', 'znajdz-synonimy', 'slowa-i-wiedza', false),
  ('audio/wyobraznia/co-oni-odpowiedzieli.m4a', 'co-oni-odpowiedzieli', 'wyobraznia', false),
  ('audio/wyobraznia/dokoncz-historie.m4a', 'dokoncz-historie', 'wyobraznia', false),
  ('audio/wyobraznia/magiczny-sklep.m4a', 'magiczny-sklep', 'wyobraznia', true),
  ('audio/wyobraznia/magiczny-teatr.m4a', 'magiczny-teatr', 'wyobraznia', false),
  ('audio/wyobraznia/mikstura.m4a', 'mikstura', 'wyobraznia', false),
  ('audio/wyobraznia/mistrz-kuchni.m4a', 'mistrz-kuchni', 'wyobraznia', false),
  ('audio/wyobraznia/moj-superbohater.m4a', 'moj-superbohater', 'wyobraznia', false),
  ('audio/wyobraznia/podroz-na-inna-planete.m4a', 'podroz-na-inna-planete', 'wyobraznia', false),
  ('audio/wyobraznia/wymysl-znaczenie.m4a', 'wymysl-znaczenie', 'wyobraznia', false),
  ('audio/wyobraznia/zaginiony-skarb.m4a', 'zaginiony-skarb', 'wyobraznia', false),
  ('games/echo-rytmu/again.m4a', 'echo-rytmu', null, false),
  ('games/echo-rytmu/heard_claps.m4a', 'echo-rytmu', null, false),
  ('games/echo-rytmu/intro.m4a', 'echo-rytmu', null, false),
  ('games/echo-rytmu/outro.m4a', 'echo-rytmu', null, false),
  ('games/echo-rytmu/rhythm_1.m4a', 'echo-rytmu', null, false),
  ('games/echo-rytmu/rhythm_2.m4a', 'echo-rytmu', null, false),
  ('games/echo-rytmu/rhythm_3.m4a', 'echo-rytmu', null, false),
  ('games/echo-rytmu/your_turn.m4a', 'echo-rytmu', null, false),
  ('games/prawda-czy-nie/a_auta.m4a', 'prawda-czy-nie', null, true),
  ('games/prawda-czy-nie/a_krowa.m4a', 'prawda-czy-nie', null, true),
  ('games/prawda-czy-nie/a_lato.m4a', 'prawda-czy-nie', null, true),
  ('games/prawda-czy-nie/a_ryby.m4a', 'prawda-czy-nie', null, true),
  ('games/prawda-czy-nie/a_slon.m4a', 'prawda-czy-nie', null, true),
  ('games/prawda-czy-nie/a_snieg.m4a', 'prawda-czy-nie', null, true),
  ('games/prawda-czy-nie/correct.m4a', 'prawda-czy-nie', null, true),
  ('games/prawda-czy-nie/intro.m4a', 'prawda-czy-nie', null, true),
  ('games/prawda-czy-nie/not_heard.m4a', 'prawda-czy-nie', null, true),
  ('games/prawda-czy-nie/oops.m4a', 'prawda-czy-nie', null, true),
  ('games/prawda-czy-nie/outro_good.m4a', 'prawda-czy-nie', null, true),
  ('games/prawda-czy-nie/outro_great.m4a', 'prawda-czy-nie', null, true),
  ('games/prawda-czy-nie/q_auta.m4a', 'prawda-czy-nie', null, true),
  ('games/prawda-czy-nie/q_krowa.m4a', 'prawda-czy-nie', null, true),
  ('games/prawda-czy-nie/q_lato.m4a', 'prawda-czy-nie', null, true),
  ('games/prawda-czy-nie/q_ryby.m4a', 'prawda-czy-nie', null, true),
  ('games/prawda-czy-nie/q_slon.m4a', 'prawda-czy-nie', null, true),
  ('games/prawda-czy-nie/q_snieg.m4a', 'prawda-czy-nie', null, true),
  ('games/prawda-czy-nie/think.m4a', 'prawda-czy-nie', null, true),
  ('games/prawda-czy-nie/thinking.m4a', 'prawda-czy-nie', null, true),
  ('games/zamrozone-raczki/go.m4a', 'zamrozone-raczki', null, false),
  ('games/zamrozone-raczki/intro.m4a', 'zamrozone-raczki', null, false),
  ('games/zamrozone-raczki/music_1.m4a', 'zamrozone-raczki', null, false),
  ('games/zamrozone-raczki/music_2.m4a', 'zamrozone-raczki', null, false),
  ('games/zamrozone-raczki/music_3.m4a', 'zamrozone-raczki', null, false),
  ('games/zamrozone-raczki/outro.m4a', 'zamrozone-raczki', null, false),
  ('games/zamrozone-raczki/stop.m4a', 'zamrozone-raczki', null, false),
  ('games/zamrozony-taniec/go.m4a', 'zamrozony-taniec', null, false),
  ('games/zamrozony-taniec/intro.m4a', 'zamrozony-taniec', null, false),
  ('games/zamrozony-taniec/music_1.m4a', 'zamrozony-taniec', null, false),
  ('games/zamrozony-taniec/music_2.m4a', 'zamrozony-taniec', null, false),
  ('games/zamrozony-taniec/music_3.m4a', 'zamrozony-taniec', null, false),
  ('games/zamrozony-taniec/outro.m4a', 'zamrozony-taniec', null, false),
  ('games/zamrozony-taniec/stop.m4a', 'zamrozony-taniec', null, false),
  ('games/zgadnij-dzwiek/a_deszcz.m4a', 'zgadnij-dzwiek', null, true),
  ('games/zgadnij-dzwiek/a_dzwonek.m4a', 'zgadnij-dzwiek', null, true),
  ('games/zgadnij-dzwiek/a_zegar.m4a', 'zgadnij-dzwiek', null, true),
  ('games/zgadnij-dzwiek/heard_you.m4a', 'zgadnij-dzwiek', null, true),
  ('games/zgadnij-dzwiek/intro.m4a', 'zgadnij-dzwiek', null, true),
  ('games/zgadnij-dzwiek/outro.m4a', 'zgadnij-dzwiek', null, true),
  ('games/zgadnij-dzwiek/q_deszcz.m4a', 'zgadnij-dzwiek', null, true),
  ('games/zgadnij-dzwiek/q_dzwonek.m4a', 'zgadnij-dzwiek', null, true),
  ('games/zgadnij-dzwiek/q_zegar.m4a', 'zgadnij-dzwiek', null, true),
  ('games/zgadnij-dzwiek/thinking.m4a', 'zgadnij-dzwiek', null, true),
  ('pdf/detektyw/gadajacy-smietnik.pdf', 'gadajacy-smietnik', 'detektyw', false),
  ('pdf/detektyw/na-ratunek-budce-z-lodami.pdf', 'na-ratunek-budce-z-lodami', 'detektyw', false),
  ('pdf/detektyw/tajemnicze-znaki.pdf', 'tajemnicze-znaki', 'detektyw', false),
  ('pdf/detektyw/zlodziej-naszyjnika.pdf', 'zlodziej-naszyjnika', 'detektyw', true),
  ('pdf/detektyw/znikajace-dzwonki.pdf', 'znikajace-dzwonki', 'detektyw', false),
  ('pdf/slowa-i-wiedza/dyplom-co-to-za-dzwiek.pdf', 'co-to-za-dzwiek', 'slowa-i-wiedza', true),
  ('pdf/slowa-i-wiedza/dyplom-co-to-za-przedmiot.pdf', 'co-to-za-przedmiot', 'slowa-i-wiedza', false),
  ('pdf/slowa-i-wiedza/dyplom-co-tu-nie-pasuje.pdf', 'co-tu-nie-pasuje', 'slowa-i-wiedza', false),
  ('pdf/slowa-i-wiedza/dyplom-dokoncz-zgodnie-z-prawda.pdf', 'dokoncz-zgodnie-z-prawda', 'slowa-i-wiedza', false),
  ('pdf/slowa-i-wiedza/dyplom-kto-to-powiedzial.pdf', 'kto-to-powiedzial', 'slowa-i-wiedza', false),
  ('pdf/slowa-i-wiedza/dyplom-szybkie-skojarzenia.pdf', 'szybkie-skojarzenia', 'slowa-i-wiedza', false),
  ('pdf/slowa-i-wiedza/dyplom-uloz-zdanie.pdf', 'uloz-zdanie', 'slowa-i-wiedza', false),
  ('pdf/slowa-i-wiedza/dyplom-wymien-trzy.pdf', 'wymien-trzy', 'slowa-i-wiedza', false),
  ('pdf/slowa-i-wiedza/dyplom-znajdz-przeciwienstwo.pdf', 'znajdz-przeciwienstwo', 'slowa-i-wiedza', false),
  ('pdf/slowa-i-wiedza/dyplom-znajdz-synonimy.pdf', 'znajdz-synonimy', 'slowa-i-wiedza', false)
on conflict (path) do update set item_id = excluded.item_id, pack_id = excluded.pack_id, free = excluded.free;
