/// Lord Von Ekran's lines. One dog, two audiences (docs/golden, "Sprawy Domowe" strategy):
/// - to the child he is warm and curious (spoken, [kidHello]);
/// - to the parent he is an officer of the Home Affairs Office: deadpan, bureaucratic, facts
///   and times, no exclamation marks, no emoji. He mocks objects and situations, never the
///   child or how the parent copes.
///
/// Parent lines are text on screen only; they never talk over an audio activity. The widget
/// gets the lighter, relatable pool ([widget]).
enum LordPool {
  launchMorning,
  launchMidday,
  launchAfternoon,
  launchEvening,
  gameListening,
  gameWaiting,
  gameFinished,
  trip,
  bedtime,
  kidsHome,
  hello,
  widgetMorning,
  widgetMidday,
  widgetAfternoon,
  widgetEvening,
}

const lordLines = <LordPool, List<String>>{
  // Start screen, once per app launch, by part of the day.
  LordPool.launchMorning: [
    'Budzik zadzwonił. Nikt go o zdanie nie pytał.',
    'Kawa zimna. Za to atmosfera przy butach gorąca.',
    'Negocjacje w sprawie skarpetek trwają. Bez postępów.',
    'Wyjście z domu, podejście trzecie. Przyjęto do akt.',
    'Tost spadł masłem w dół. Ja nazywam to dostawą.',
    'Poranek. Nawet mój ogon prosi o pięć minut.',
    'Budzik ma jedną pracę. I wszyscy go za nią nie lubią.',
    'Kawa przed rozmową. To nie rytuał. To zabezpieczenie.',
    'Plan był wstać wcześniej. Plan najwyraźniej zaspał.',
    'Płatki na podłodze. Śniadanie w terenie.',
    'Skarpetki do pary? Widzę, że dziś na bogato.',
    'Wyjście o ósmej. Nie ustaliliśmy tylko dnia.',
    'Ten włos na głowie? Antena do odbioru chaosu.',
    'Kanapka w pudełku. Pudełko w domu. Klasyka gatunku.',
    'Pralka oddała jedną skarpetkę. Pobiera prowizję.',
  ],
  LordPool.launchMidday: [
    'Za cicho. Albo cud, albo ściana ma nowy kolor.',
    'Klocek pod stopą. Domowe spa w wersji hard.',
    'Zabawka: 200 zł. Karton: hit sezonu. Bez komentarza.',
    'Obiad przyjęty warunkowo. Marchewka odrzucona.',
    'Pisak zatrzymany przy ścianie. Ściana nie wnosi skarg.',
    'Pranie samo się nie złoży. Sprawdzam od lat.',
    'Stół lepki. Czyli obiad trzyma poziom.',
    'Pod kanapą znalazłem obiad. Rocznik nieczytelny.',
    'Porządek to ten moment między dwoma kichnięciami.',
    'Zmywarka skończyła. Teraz udajemy, że nie słyszymy.',
    'Dywan ma okruchy. Wreszcie coś z dodatkami.',
    'Lista zadań rośnie. Chyba ktoś ją podlewa.',
    'Kupiłem organizer. Teraz bałagan ma mieszkanie.',
    'Zupa ma grudki. Szef kuchni nazywa to fabułą.',
    'Stół przetarty. Keczup przyjął to jako wyzwanie.',
  ],
  LordPool.launchAfternoon: [
    'Droga z przedszkola. Dziewiętnaście pytań „dlaczego”.',
    '17:40. Plac zabaw odmawia wydania dziecka.',
    'Nawigacja mówi „za chwilę”. Też ma dzieci?',
    'Tylna kanapa auta: okruchy. Pochodzenie nieustalone.',
    'Kurtka założona. Czapka zaginęła w akcji.',
    'Plan na popołudnie? Przetrwać do kapci.',
    'Plac zabaw. Siłownia z piaskiem w majtkach.',
    'W kieszeni kamień. Pamiątka z epoki przed obiadem.',
    'Kałuża była mała. Spodnie mają inne zeznania.',
    'Torba na spacer waży tyle, co krótki urlop.',
    'Zakupy z listą. Lista została na lodówce. Pilnuje.',
    'Parasola nie ma. Prognoza właśnie się uśmiechnęła.',
    'Przekąska awaryjna zjedzona. Awaria dopiero idzie.',
    'Winda nie działa. Dziś nogi mają zebranie.',
    'Buty pełne piasku. Działka nad morzem już jest.',
  ],
  LordPool.launchEvening: [
    '20:00. Rozpoczęto negocjacje w sprawie piżamy.',
    'Kąpiel zakończona. Łazienka w trakcie oględzin.',
    'Jeszcze jedna bajka. Wniosek rozpatrywany.',
    'Szklanka wody numer trzy. Przyjęto do akt.',
    'Dom posprzątany. Zdjęcie zrobione. Dowód mamy.',
    'Piżama założona. Komisja do spraw snu obraduje.',
    'Wanna opróżniona. Ocean przeniósł się na podłogę.',
    'Wreszcie wieczór. Pranie patrzy. Nie patrz mu w oczy.',
    'Plan: serial. Odcinek: zamknięte powieki.',
    'Kolacja przy świecach. Bo żarówka czeka od wtorku.',
    'Kanapa rozłożona. Ambicje też.',
    'Pilot zaginął. Dziś oglądamy poszukiwania.',
    'Zgaszone światło. Aktywowany czujnik chrupania.',
    'Herbata na wieczór. Zaparzyła się już rano.',
    'Dzień zaliczony. Styl dowolny. Lądowanie na kanapie.',
  ],
  // While Lord is gentle with the child, a line for the parent on the screen.
  LordPool.gameListening: [
    'Przesłuchanie trwa. Świadek odpowiada klaśnięciem.',
    'Usiądź. Jeśli kanapa pyta, jesteś na szkoleniu.',
    'Dziecko myśli. Ty możesz usiąść.',
    'Ekran leży. Świadek zajęty. Kawa jeszcze ciepła.',
    'Ja prowadzę zabawę. Ty negocjuj z oparciem.',
    'Uszy pracują. Ekran pierwszy raz ma wolne.',
    'Telefon leży spokojnie. Też jest w szoku.',
    'Kawa czeka. Idź, zanim zmieni stan skupienia.',
    'Nie musisz klaskać. Przyjmuję też kiwnięcie kubkiem.',
    'Zagadka w toku. Pranie nie zna odpowiedzi. Ignoruj.',
    'To dobry moment, żeby zjeść coś bez dzielenia.',
    'Słuchamy. Lodówka może na chwilę przestać buczeć.',
    'Możesz oprzeć plecy. Tak, całe.',
    'Prowadzę. Ty zdejmij z siebie funkcję kierownika.',
  ],
  LordPool.gameWaiting: [
    'Czas na odpowiedź. Rodzic milczy jak kamień.',
    'Chwila namysłu. Ja też tak mam przed lodówką.',
    'Świadek się zastanawia. Sąd czeka cierpliwie.',
    'Czekamy. Nawet mój ogon dostał zakaz podpowiadania.',
    'Myślenie trwa. Nie da się przyspieszyć potrząsaniem.',
    'Mózg pracuje. Kółka nie widać, ale się kręci.',
    'Cierpliwość. To nie mikrofalówka, nie będzie pik.',
    'Dajmy chwilę. Dobry pomysł szuka drugiego buta.',
    'Odpowiedź dojrzewa. Jak banan, tylko mniej plam.',
    'Czekam spokojnie. Za szynkę umiem nawet dłużej.',
    'Cisza robocza. Remont w dziale pomysłów.',
    'Nie poganiamy. Ja własny ogon gonię od lat.',
    'Chwila pauzy. Nawet geniusz musi przełknąć ślinę.',
  ],
  LordPool.gameFinished: [
    'Sprawa zamknięta. Nikt nie patrzył w ekran.',
    'Brawa dla ekipy. Ja klaskam ogonem. Mam patent.',
    'Zabawa zakończona. Akta trafiają do szuflady.',
  ],
  LordPool.trip: [
    'Kierowca skupiony. Tylne siedzenie zajęte zagadką.',
    '„Daleko jeszcze” odroczone o kwadrans.',
    'Trasa: 40 minut. Pytań: nieograniczona liczba.',
    'Postój na stacji nie jest planowany. Na razie.',
    'GPS przelicza trasę. Ja przeliczam herbatniki.',
    'Bagażnik zamknięty. Metodą wiary i docisku.',
    'To nie korek. To parking z fabułą.',
    'Walizka na dwa dni. Zawartość na zmianę kontynentu.',
    'Przerwa na siku. Tradycja silniejsza od rozkładu.',
    'Widok za oknem piękny. Okruchy też robią krajobraz.',
    'Nawigacja zna skrót. Zawieszenie już się boi.',
    'Klimatyzacja: jedna osoba marznie, druga ma lato.',
    'Zgubiliśmy zasięg. Rozmowa rodzinna ładuje się sama.',
    'Do celu 20 minut. W jednostkach „już?” jakieś 80.',
  ],
  LordPool.bedtime: [
    'Tryb wieczorny. Lord mówi szeptem. Ty też.',
    'Podłoga skrzypi tylko po dobranoc. Donosicielka.',
    'Po dobranoc kanapa jest twoja. Do odwołania.',
    'Negocjacje zakończone. Strony zmęczone, ale zadowolone.',
    'Klamka kliknęła jak wystrzał. Zdrajczyni.',
    'Skradam się. Godność zostawiłem przy skrzypiącej desce.',
    'Kołdra ma dwie strony. Obie właśnie zajęte.',
    'Dobranoc. Lodówko, ty nie śpisz, prawda?',
    'Nocna cisza. Idealna pora, żeby upuścić łyżeczkę.',
    'Misja: wyjść z pokoju. Poziom: folia pod stopą.',
    'Kołysanka działa. Rodzic odpadł w pierwszej rundzie.',
    'Poduszka pyta o plany. Mówię: związek na stałe.',
    'Czas spać. Rachunki mogą straszyć jutro.',
    'Drzwi zamknięte. Teraz kaszlemy do ręcznika.',
  ],
  LordPool.kidsHome: [
    'Tryb dziecka. Zakupy zablokowane. Portfel dziękuje.',
    'Dziecko wybiera samo. Ty wybierasz kawę.',
    'Strefa dziecka. Rodzic przebywa tu gościnnie.',
  ],
  // The "meet me" sheet on Start: a little longer, still dry.
  LordPool.hello: [
    'Lord Von Ekran. Rodowód mam. Maniery zjadłem. Były zawinięte w szynkę.',
    'Nie oceniam bałaganu. Widziałem, jak odkurzacz zawrócił. Szanuję jego decyzję.',
    'Pięć minut dla siebie? Siadaj. Jak ktoś pyta, to konsultacja z lordem.',
    'Zjadłem pracę domową. Dziecko jeszcze nie chodzi do szkoły. Lubię mieć zapas.',
    'Miałem być psem stróżującym. Ale ktoś otworzył lodówkę i zmieniłem dział.',
    'Mam złote serce. Reszta sierści gratis do każdej kanapy.',
    'Nie jestem rozpieszczony. Mam po prostu bardzo dobrze wyszkolonych ludzi.',
    'Mój trener mówił „zostaw”. Zostawiłem trenera. Ciastko było bliżej.',
    'Mam sześciopak. Pod futrem. I kilkoma bardzo dobrymi decyzjami kulinarnymi.',
    'Nie chrapię. Mruczę z rozmachem architektonicznym.',
    'Miałem dziś pobiegać. Ale nie chciałem psuć niespodzianki kolanom.',
    'Jestem rasowy. Rasa: ostatni przy stole.',
    'Słuch mam doskonały. „Spacer” słyszę przez ścianę. „Zejdź” jakoś gorzej.',
    'Szklanka do połowy pełna czy pusta? Ważniejsze, kto zostawił kanapkę.',
    'Nie ukradłem sera. Przeprowadziłem ewakuację z niezabezpieczonego talerza.',
  ],
  // Home-screen widget: lighter lines a parent can recognise themselves in.
  LordPool.widgetMorning: [
    'Ty ogarnij kawę. Ja ogarnę zagadki.',
    'Drugi but się znajdzie. Zwykle pod kanapą.',
    'Pięć minut spokoju? Pakiet luksusowy.',
    'Kawa znowu zimna. Powiedz, że to cold brew.',
    'Dzień dobry. Reklamacje przyjmuje poduszka.',
    'Kawa gotowa. Człowiek jeszcze się aktualizuje.',
    'Wstań i zabłyśnij. Albo wstań. Nie przesadzajmy.',
  ],
  LordPool.widgetMidday: [
    'Cisza w domu? Sprawdź, co robi pisak.',
    'Klocek wciąż na wolności. Uważaj na stopy.',
    'Brokuł uniewinniony. I tak nikt go nie ruszy.',
    'Ja mam zagadkę. Ty masz chwilę dla siebie.',
    'Obiad na czas. Czas nie został sprecyzowany.',
    'Kurz wrócił. Chyba ma tu meldunek.',
    'Pranie czeka. Jest w tym naprawdę wybitne.',
  ],
  LordPool.widgetAfternoon: [
    'Zanim padnie „daleko jeszcze?”, włącz zagadkę.',
    'Korek to też przygoda. Podobno.',
    'Plac zabaw nie odda dziecka bez negocjacji.',
    'Tylna kanapa pełna okruchów. Nie pytaj.',
    'Bateria: 8 procent. Mówię o sobie.',
    'Kanapa dzwoniła. Pyta, czy żyjesz.',
  ],
  LordPool.widgetEvening: [
    'Kołysanka dla dziecka, cisza dla ciebie.',
    'Negocjacje o piżamę? Mam argumenty.',
    'Trzecia szklanka wody. Śpimy czy hodujemy ryż?',
    'Po dobranoc kanapa jest twoja.',
    'Dziś już nic nie musisz. Powiedz to zmywarce.',
    'Otwieraj chipsy. Powoli. To operacja specjalna.',
  ],
};

/// Line [index] of [pool], wrapping around.
String lordLine(LordPool pool, int index) {
  final lines = lordLines[pool]!;
  return lines[index % lines.length];
}
