/// Szop’en von Ekran's lines. One raccoon, two audiences (docs/golden, "Sprawy Domowe" strategy):
/// - to the child he is warm and curious (spoken, [kidHello]);
/// - to the parent he is an officer of the Home Affairs Office: deadpan, bureaucratic, facts
///   and times, no exclamation marks, no emoji. He mocks objects and situations, never the
///   child or how the parent copes.
///
/// Parent lines are text on screen only; they never talk over an audio activity. The widget
/// gets the lighter, relatable pool ([widget]).
enum LordPool {
  launchMorning,
  launchMidday,
  launchAfternoon,
  launchEvening,
  gameListening,
  gameWaiting,
  gameFinished,
  trip,
  bedtime,
  kidsHome,
  hello,
  widgetMorning,
  widgetMidday,
  widgetAfternoon,
  widgetEvening,
}

const lordLines = <LordPool, List<String>>{
  // Start screen, once per app launch, by part of the day.
  LordPool.launchMorning: [
    'Budzik zadzwonił. Nikt go o zdanie nie pytał.',
    'Kawa zimna. Za to atmosfera przy butach gorąca.',
    'Negocjacje w sprawie skarpetek trwają. Bez postępów.',
    'Wyjście z domu, podejście trzecie. Przyjęto do akt.',
    'Tost spadł masłem w dół. Ja nazywam to dostawą.',
    'Jestem w pracy. Nie mylmy tego z gotowością.',
    'Budzik ma jedną pracę. I wszyscy go za nią nie lubią.',
    'Kawa przed rozmową. To nie rytuał. To zabezpieczenie.',
    'Zaspałem. Na szczęście zawodowo wyglądam na zajętego.',
    'Płatki na podłodze. Śniadanie w terenie.',
    'Skarpetki do pary? Widzę, że dziś na bogato.',
    'Wyjście o ósmej. Nie ustaliliśmy tylko dnia.',
    'Ten włos na głowie? Antena do odbioru chaosu.',
    'Kanapka w pudełku. Pudełko w domu. Klasyka gatunku.',
    'Pralka oddała jedną skarpetkę. Pobiera prowizję.',
  ],
  LordPool.launchMidday: [
    'Za cicho. Albo cud, albo ściana ma nowy kolor.',
    'Klocek pod stopą. Domowe spa w wersji hard.',
    'Zabawka: 200 zł. Karton: hit sezonu. Bez komentarza.',
    'Obiad przyjęty warunkowo. Marchewka odrzucona.',
    'Pisak zatrzymany przy ścianie. Ściana nie wnosi skarg.',
    'Pranie samo się nie złoży. Sprawdzam od lat.',
    'Stół lepki. Czyli obiad trzyma poziom.',
    'Pod kanapą znalazłem obiad. Rocznik nieczytelny.',
    'Porządek to ten moment między dwoma kichnięciami.',
    'Zmywarka skończyła. Teraz udajemy, że nie słyszymy.',
    'Dywan ma okruchy. Wreszcie coś z dodatkami.',
    'Odznaczyłem zadanie. Nie swoje. Ale miło było.',
    'Kupiłem organizer. Teraz bałagan ma mieszkanie.',
    'Zupa ma grudki. Szef kuchni nazywa to fabułą.',
    'Stół przetarty. Keczup przyjął to jako wyzwanie.',
  ],
  LordPool.launchAfternoon: [
    'Droga z przedszkola. Dziewiętnaście pytań „dlaczego”.',
    '17:40. Plac zabaw odmawia wydania dziecka.',
    'Nawigacja mówi „za chwilę”. Też ma dzieci?',
    'Tylna kanapa auta: okruchy. Pochodzenie nieustalone.',
    'Kurtka założona. Czapka zaginęła w akcji.',
    'Jeszcze jedna sprawa i kończę. Mówię tak od rana.',
    'Plac zabaw. Siłownia z piaskiem w majtkach.',
    'W kieszeni kamień. Pamiątka z epoki przed obiadem.',
    'Kałuża była mała. Spodnie mają inne zeznania.',
    'Torba na spacer waży tyle, co krótki urlop.',
    'Zakupy z listą. Lista została na lodówce. Pilnuje.',
    'Parasola nie ma. Prognoza właśnie się uśmiechnęła.',
    'Przekąska awaryjna zjedzona. Awaria dopiero idzie.',
    'Winda nie działa. Dziś nogi mają zebranie.',
    'Buty pełne piasku. Działka nad morzem już jest.',
  ],
  LordPool.launchEvening: [
    '20:00. Rozpoczęto negocjacje w sprawie piżamy.',
    'Kąpiel zakończona. Łazienka w trakcie oględzin.',
    'Jeszcze jedna bajka. Wniosek rozpatrywany.',
    'Szklanka wody numer trzy. Przyjęto do akt.',
    'Dom posprzątany. Zdjęcie zrobione. Dowód mamy.',
    'Piżama założona. Komisja do spraw snu obraduje.',
    'Wanna opróżniona. Ocean przeniósł się na podłogę.',
    'Wreszcie wieczór. Pranie patrzy. Nie patrz mu w oczy.',
    'Plan: serial. Odcinek: zamknięte powieki.',
    'Kolacja przy świecach. Bo żarówka czeka od wtorku.',
    'Dziś dałem z siebie wszystko. Czyli dostępne 12%.',
    'Pilot zaginął. Dziś oglądamy poszukiwania.',
    'Zgaszone światło. Aktywowany czujnik chrupania.',
    'Herbata na wieczór. Zaparzyła się już rano.',
    'Dzień zaliczony. Styl dowolny. Lądowanie na kanapie.',
  ],
  // While Szop’en is gentle with the child, a line for the parent on the screen.
  LordPool.gameListening: [
    'Zabawa działa. Proszę zapisać, że to moja zasługa.',
    'Usiądź. Jeśli kanapa pyta, jesteś na szkoleniu.',
    'Dziecko myśli. Ty możesz usiąść.',
    'Ekran leży. Świadek zajęty. Kawa jeszcze ciepła.',
    'Ja prowadzę zabawę. Ty negocjuj z oparciem.',
    'Uszy pracują. Ekran pierwszy raz ma wolne.',
    'Telefon leży spokojnie. Też jest w szoku.',
    'Kawa czeka. Idź, zanim zmieni stan skupienia.',
    'Nie musisz klaskać. Przyjmuję też kiwnięcie kubkiem.',
    'Zagadka w toku. Pranie nie zna odpowiedzi. Ignoruj.',
    'To dobry moment, żeby zjeść coś bez dzielenia.',
    'Słuchamy. Lodówka może na chwilę przestać buczeć.',
    'Możesz oprzeć plecy. Tak, całe.',
    'Prowadzę. Ty zdejmij z siebie funkcję kierownika.',
  ],
  LordPool.gameWaiting: [
    'Czekamy na pomysł. Spotkanie bez prezentacji. Cud.',
    'Chwila namysłu. Ja też tak mam przed lodówką.',
    'Myślimy. Ja też tak wyglądam, kiedy nic nie robię.',
    'Czekamy. Nawet mój ogon dostał zakaz podpowiadania.',
    'Myślenie trwa. Nie da się przyspieszyć potrząsaniem.',
    'Mózg pracuje. Kółka nie widać, ale się kręci.',
    'Cierpliwość. To nie mikrofalówka, nie będzie pik.',
    'Dajmy chwilę. Dobry pomysł szuka drugiego buta.',
    'Odpowiedź dojrzewa. Jak banan, tylko mniej plam.',
    'Czekam spokojnie. Za szynkę umiem nawet dłużej.',
    'Cisza robocza. Remont w dziale pomysłów.',
    'Nie poganiamy. Dobry pomysł nie odbija karty.',
    'Chwila pauzy. Nawet geniusz musi przełknąć ślinę.',
  ],
  LordPool.gameFinished: [
    'Sprawa zamknięta. Nikt nie patrzył w ekran.',
    'Brawa dla ekipy. Ja klaskam ogonem. Mam patent.',
    'Zrobione. Teraz będę o tym mówił na każdym zebraniu.',
  ],
  LordPool.trip: [
    'Kierowca skupiony. Tylne siedzenie zajęte zagadką.',
    '„Daleko jeszcze” odroczone o kwadrans.',
    'Trasa: 40 minut. Pytań: nieograniczona liczba.',
    'Postój na stacji nie jest planowany. Na razie.',
    'GPS przelicza trasę. Ja przeliczam herbatniki.',
    'Bagażnik zamknięty. Metodą wiary i docisku.',
    'To nie korek. To parking z fabułą.',
    'Walizka na dwa dni. Zawartość na zmianę kontynentu.',
    'Przerwa na siku. Tradycja silniejsza od rozkładu.',
    'Widok za oknem piękny. Okruchy też robią krajobraz.',
    'Nawigacja zna skrót. Zawieszenie już się boi.',
    'Klimatyzacja: jedna osoba marznie, druga ma lato.',
    'Zgubiliśmy zasięg. Rozmowa rodzinna ładuje się sama.',
    'Do celu 20 minut. W jednostkach „już?” jakieś 80.',
  ],
  LordPool.bedtime: [
    'Cicho. Zmiana nocna nie wie, że to też ja.',
    'Podłoga skrzypi tylko po dobranoc. Donosicielka.',
    'Dobranoc. Nadgodziny proszę zgłaszać poduszce. Do odwołania.',
    'Negocjacje zakończone. Strony zmęczone, ale zadowolone.',
    'Klamka kliknęła jak wystrzał. Zdrajczyni.',
    'Skradam się. Godność zostawiłem przy skrzypiącej desce.',
    'Kołdra ma dwie strony. Obie właśnie zajęte.',
    'Dobranoc. Lodówko, ty nie śpisz, prawda?',
    'Nocna cisza. Idealna pora, żeby upuścić łyżeczkę.',
    'Misja: wyjść z pokoju. Poziom: folia pod stopą.',
    'Kołysanka działa. Rodzic odpadł w pierwszej rundzie.',
    'Poduszka pyta o plany. Mówię: związek na stałe.',
    'Czas spać. Rachunki mogą straszyć jutro.',
    'Drzwi zamknięte. Teraz kaszlemy do ręcznika.',
  ],
  LordPool.kidsHome: [
    'Tryb dziecka. Zakupy zablokowane. Portfel dziękuje.',
    'Dziecko wybiera samo. Ty wybierasz kawę.',
    'Strefa dziecka. Rodzic przebywa tu gościnnie.',
  ],
  // The "meet me" sheet on Start: a little longer, still dry.
  LordPool.hello: [
    'Mam plan. Prosty, skuteczny i opracowany przez kogoś, kto też nie ma siły.',
    'Dziecko pyta „dlaczego”. Ty pytasz „ile jeszcze”. Obsługuję oba działy.',
    'AudioKiddo płaci mi za pomysły. Na szczęście nie za entuzjazm.',
    '„Ubierz buty” to nie polecenie. To początek negocjacji międzynarodowych.',
    'Cisza w pokoju dziecięcym? Nie gratuluj sobie jeszcze. Zrób rekonesans.',
    'Mam otwarte 14 spraw. Głównie szafek. Szukam ciastek.',
    'Szef pytał, czy ogarniam. Odpowiedziałem pytaniem. To się nazywa doświadczenie.',
    'Plan dnia był świetny. Niestety dziecko nie uczestniczyło w jego zatwierdzaniu.',
    'Nie oceniajmy dnia przed ostatnim „chcę pić”. To błąd metodologiczny.',
    'Znam sposób na pięć minut spokoju. Dziesięć to już dział badań i rozwoju.',
    '„Zaraz” u rodzica trwa minutę. U dziecka obejmuje kilka epok geologicznych.',
    'Nie odkładam pracy. Pozwalam, żeby część problemów rozwiązała się ze starości.',
    'Widzę, że pijesz zimną kawę. Miło spotkać kogoś z podobnym stażem.',
    'Pracuję pod presją. Głównie małych osób pytających, co jest na obiad.',
    'Zróbmy krótką zabawę. Długie mamy już zebranie w sprawie jednej skarpetki.',
    'Moje KPI? Kawa Przed Interakcją. Wyniki są obiecujące.',
  ],
  // Home-screen widget: lighter lines a parent can recognise themselves in.
  LordPool.widgetMorning: [
    'Ty ogarnij kawę. Ja ogarnę zagadki.',
    'Drugi but się znajdzie. Zwykle pod kanapą.',
    'Włącz zabawę. Muszę wykazać jakąś aktywność.',
    'Kawa znowu zimna. Powiedz, że to cold brew.',
    'Dzień dobry. Reklamacje przyjmuje poduszka.',
    'Kawa gotowa. Człowiek jeszcze się aktualizuje.',
    'Wstań i zabłyśnij. Albo wstań. Nie przesadzajmy.',
  ],
  LordPool.widgetMidday: [
    'Cisza w domu? Sprawdź, co robi pisak.',
    'Klocek wciąż na wolności. Uważaj na stopy.',
    'Brokuł uniewinniony. I tak nikt go nie ruszy.',
    'Mam zabawę. Wygląda na to, że dziś jednak pracuję.',
    'Obiad na czas. Czas nie został sprecyzowany.',
    'Kurz wrócił. Chyba ma tu meldunek.',
    'Pranie czeka. Jest w tym naprawdę wybitne.',
  ],
  LordPool.widgetAfternoon: [
    'Zanim padnie „daleko jeszcze?”, włącz zagadkę.',
    'Korek to też przygoda. Podobno.',
    'Plac zabaw nie odda dziecka bez negocjacji.',
    'Tylna kanapa pełna okruchów. Nie pytaj.',
    'Przypominam o zabawie. Szef patrzy na wyniki.',
    'Kanapa dzwoniła. Pyta, czy żyjesz.',
  ],
  LordPool.widgetEvening: [
    'Kołysanka dla dziecka, cisza dla ciebie.',
    'Negocjacje o piżamę? Mam argumenty.',
    'Trzecia szklanka wody. Śpimy czy hodujemy ryż?',
    'Dobranoc. Nadgodziny proszę zgłaszać poduszce.',
    'Dziś już nic nie musisz. Powiedz to zmywarce.',
    'Otwieraj chipsy. Powoli. To operacja specjalna.',
  ],
};

/// Line [index] of [pool], wrapping around.
String lordLine(LordPool pool, int index) {
  final lines = lordLines[pool]!;
  return lines[index % lines.length];
}
